import os
import re
import json
import math
from collections import Counter
from functools import lru_cache

import cv2
import numpy as np
import PIL
import torch
from PIL import ExifTags, Image, PngImagePlugin, UnidentifiedImageError
from transformers import CLIPModel, CLIPProcessor

if not hasattr(PIL, "PngImagePlugin"):
    PIL.PngImagePlugin = PngImagePlugin


LOW_FAKE_THRESHOLD = 0.35
HIGH_FAKE_THRESHOLD = 0.65
MAX_FALLBACK_CONFIDENCE = 0.40
MAX_DOCUMENT_BYTES = 2_000_000
MODEL_INPUT_SIZE = (224, 224)
GEMINI_MODEL_NAME = os.getenv("GEMINI_MODEL_NAME", "gemini-2.5-flash").strip() or "gemini-2.5-flash"
CLIP_MODEL_NAME = os.getenv("CLIP_MODEL_NAME", "openai/clip-vit-base-patch32").strip() or "openai/clip-vit-base-patch32"
CLIP_PROMPT_PAIRS = [
    {
        "real": "an authentic portrait photo of a real person",
        "fake": "a deepfake portrait of a person",
    },
    {
        "real": "a genuine unedited face photograph",
        "fake": "a manipulated or synthetic face image",
    },
    {
        "real": "a natural camera photo of a human face",
        "fake": "an AI-generated or face-swapped human image",
    },
]

GEMINI_IMAGE_PROMPT = """You are an AI forensics expert. Analyze this image and determine if it is 
AI-generated, manipulated, or authentic. 

Respond ONLY in this exact JSON format with no extra text:
{
  "verdict": "REAL" or "FAKE" or "UNCERTAIN",
  "confidence": 0.0 to 1.0,
  "fake_probability": 0.0 to 1.0,
  "risk_score": 0 to 100,
  "risk_level": "LOW" or "MEDIUM" or "HIGH" or "CRITICAL",
  "signals": {
    "gemini_verdict": "one line explanation",
    "artifacts_detected": true or false,
    "lighting_inconsistency": true or false,
    "texture_anomaly": true or false,
    "metadata_status": "present" or "missing" or "suspicious",
    "source": "gemini"
  }
}"""

GEMINI_DOCUMENT_PROMPT_TEMPLATE = """You are an AI text forensics expert. Analyze the following text and determine 
if it was written by a human or generated by an AI system.

Text to analyze:
{text}

Respond ONLY in this exact JSON format with no extra text:
{
  "verdict": "REAL" or "FAKE" or "UNCERTAIN",
  "confidence": 0.0 to 1.0,
  "fake_probability": 0.0 to 1.0,
  "risk_score": 0 to 100,
  "risk_level": "LOW" or "MEDIUM" or "HIGH" or "CRITICAL",
  "signals": {
    "gemini_verdict": "one line explanation",
    "repetition_detected": true or false,
    "unnatural_fluency": true or false,
    "vocabulary_diversity": "low" or "medium" or "high",
    "source": "gemini"
  }
}"""

if not os.getenv("GEMINI_API_KEY"):
    print("[VerifyMe] WARNING: GEMINI_API_KEY not set. Running in heuristic fallback mode.", flush=True)


def _clamp(value: float, minimum: float = 0.0, maximum: float = 1.0) -> float:
    return max(minimum, min(maximum, float(value)))


def _percent(value: float) -> str:
    return f"{_clamp(value) * 100:.2f}%"


def _to_risk_score(fake_score: float) -> int:
    clamped_score = _clamp(fake_score)
    if clamped_score <= 0.0:
        return 0
    return min(100, max(1, int(math.ceil(clamped_score * 100))))


def _risk_level(fake_score: float) -> str:
    if fake_score >= 0.75:
        return "High"
    if fake_score >= 0.5:
        return "Medium"
    if fake_score >= 0.25:
        return "Low"
    return "Minimal"


def _gemini_risk_level(fake_score: float) -> str:
    if fake_score >= 0.85:
        return "CRITICAL"
    if fake_score >= 0.65:
        return "HIGH"
    if fake_score >= 0.35:
        return "MEDIUM"
    return "LOW"


def _gemini_prediction(fake_score: float) -> str:
    if fake_score > 0.6:
        return "FAKE"
    if fake_score < 0.35:
        return "REAL"
    return "UNCERTAIN"


def _classify_fake_score(fake_score: float, model_loaded: bool) -> str:
    if not model_loaded:
        return "Uncertain"
    if fake_score < LOW_FAKE_THRESHOLD:
        return "Likely Real"
    if fake_score > HIGH_FAKE_THRESHOLD:
        return "Likely Fake"
    return "Uncertain"


def _prediction_confidence(fake_score: float, prediction: str, source: str) -> float:
    normalized_prediction = str(prediction).strip().upper()
    if "UNCERTAIN" in normalized_prediction:
        confidence = MAX_FALLBACK_CONFIDENCE
    elif "FAKE" in normalized_prediction:
        confidence = fake_score
    elif "REAL" in normalized_prediction:
        confidence = 1.0 - fake_score
    else:
        confidence = MAX_FALLBACK_CONFIDENCE
    return _clamp(max(confidence, 0.01))


def _log_gemini_error(error: Exception) -> None:
    print(f"[VerifyMe Gemini Error] {error}", flush=True)


@lru_cache(maxsize=1)
def _get_gemini_model():
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        return None

    try:
        import google.generativeai as genai

        genai.configure(api_key=api_key)
        return genai.GenerativeModel(GEMINI_MODEL_NAME)
    except Exception as exc:
        _log_gemini_error(exc)
        return None


def _extract_gemini_text(response) -> str:
    text = getattr(response, "text", "") or ""
    if text:
        return text.strip()

    candidates = getattr(response, "candidates", None) or []
    for candidate in candidates:
        content = getattr(candidate, "content", None)
        parts = getattr(content, "parts", None) if content else None
        if not parts:
            continue
        extracted = "".join(str(getattr(part, "text", "") or "") for part in parts).strip()
        if extracted:
            return extracted

    raise ValueError("Gemini returned an empty response")


def _parse_gemini_json(response) -> dict:
    text = _extract_gemini_text(response)
    text = text.strip()

    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.IGNORECASE)
        text = re.sub(r"\s*```$", "", text)

    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError(f"Gemini response did not contain JSON: {text[:300]}")

    return json.loads(text[start : end + 1])


def _normalize_gemini_payload(payload: dict) -> dict:
    fake_probability = _clamp(float(payload.get("fake_probability", 0.5)))
    risk_score = int(_clamp(float(payload.get("risk_score", _to_risk_score(fake_probability))), 0, 100))
    if "fake_probability" not in payload:
        fake_probability = _clamp(risk_score / 100)

    verdict = str(payload.get("verdict") or _gemini_prediction(fake_probability)).strip().upper()
    if verdict not in {"REAL", "FAKE", "UNCERTAIN"}:
        verdict = _gemini_prediction(fake_probability)

    risk_level = str(payload.get("risk_level") or _gemini_risk_level(fake_probability)).strip().upper()
    if risk_level not in {"LOW", "MEDIUM", "HIGH", "CRITICAL"}:
        risk_level = _gemini_risk_level(fake_probability)

    confidence = _clamp(float(payload.get("confidence", 0.0)))
    signals = payload.get("signals") if isinstance(payload.get("signals"), dict) else {}
    signals = {
        **signals,
        "source": "gemini",
        "model_loaded": True,
    }

    return {
        "verdict": verdict,
        "prediction": verdict,
        "confidence": confidence,
        "fake_probability": fake_probability,
        "risk_score": risk_score,
        "risk_level": risk_level,
        "signals": signals,
    }


def _format_gemini_result(asset_type: str, payload: dict, details: dict = None) -> dict:
    details = details or {}
    details.update(
        {
            "fake_probability": payload["fake_probability"],
            "gemini": {
                "model": GEMINI_MODEL_NAME,
                "verdict": payload["verdict"],
                "confidence": payload["confidence"],
                "risk_score": payload["risk_score"],
                "risk_level": payload["risk_level"],
            },
        }
    )

    return {
        "type": asset_type,
        "prediction": payload["prediction"],
        "confidence": _percent(payload["confidence"]),
        "source": "gemini",
        "model_loaded": True,
        "reliability_score": round(_clamp(payload["confidence"]), 4),
        "metadata_status": payload["signals"].get("metadata_status", "not_applicable"),
        "risk_level": payload["risk_level"],
        "details": details,
        "risk_score": payload["risk_score"],
        "verdict": payload["verdict"],
        "signals": {
            **payload["signals"],
            "fake_score": payload["fake_probability"],
            "source": "gemini",
            "model_loaded": True,
            "risk_level": payload["risk_level"],
        },
    }


def _generate_gemini_image_explanation(image: Image.Image, score: float) -> str:
    model = _get_gemini_model()
    if model is None:
        return "Explanation unavailable"

    prompt = (
        f"This image has a deepfake probability score of {score:.4f}. "
        "In 2 sentences, explain what visual signals might indicate "
        "this. Be specific about artifacts, lighting, or texture."
    )

    try:
        response = model.generate_content([prompt, image])
        text = _extract_gemini_text(response)
        return text or "Explanation unavailable"
    except Exception as exc:
        _log_gemini_error(exc)
        return "Explanation unavailable"


def _analyze_document_with_gemini(text: str, extracted: dict) -> dict:
    model = _get_gemini_model()
    if model is None:
        return None

    try:
        prompt = GEMINI_DOCUMENT_PROMPT_TEMPLATE.replace("{text}", text[:3000])
        response = model.generate_content(prompt)
        payload = _normalize_gemini_payload(_parse_gemini_json(response))
        details = {
            "metadata_status": "not_applicable",
            "metadata": {
                "byte_count": extracted["byte_count"],
                "truncated": extracted["truncated"],
                "extraction_method": extracted["extraction_method"],
            },
            "text_preview_chars": min(len(text), 3000),
        }
        return _format_gemini_result("document", payload, details)
    except Exception as exc:
        _log_gemini_error(exc)
        return None


def _generate_gemini_video_explanation(frame: Image.Image, score: float) -> str:
    return _generate_gemini_image_explanation(frame, score)


@lru_cache(maxsize=1)
def load_model() -> dict:
    print("Loading CLIP model...", flush=True)
    print(f"CLIP model: {CLIP_MODEL_NAME}", flush=True)

    try:
        device = "cuda" if torch.cuda.is_available() else "cpu"
        model = CLIPModel.from_pretrained(CLIP_MODEL_NAME)
        processor = CLIPProcessor.from_pretrained(CLIP_MODEL_NAME)
        model.eval()
        model.to(device)
    except Exception as exc:
        print("Model loaded status: false", flush=True)
        print(f"Model load error: {exc}", flush=True)
        return {
            "model": None,
            "processor": None,
            "device": "cpu",
            "model_loaded": False,
            "model_name": CLIP_MODEL_NAME,
            "error": str(exc),
        }

    print("Model loaded successfully", flush=True)
    print("Model loaded status: true", flush=True)
    return {
        "model": model,
        "processor": processor,
        "device": device,
        "model_loaded": True,
        "model_name": CLIP_MODEL_NAME,
        "error": "",
    }


@lru_cache(maxsize=1)
def load_keras_model() -> dict:
    model_path = os.getenv("IMAGE_MODEL_PATH", "").strip()
    if not model_path:
        return {"model": None, "model_loaded": False, "model_name": "Keras", "error": "IMAGE_MODEL_PATH is not set"}
    if not os.path.exists(model_path):
        fallback_model_path = os.path.join(os.path.dirname(__file__), os.path.basename(model_path))
        if os.path.exists(fallback_model_path):
            model_path = fallback_model_path
        else:
            return {
                "model": None,
                "model_loaded": False,
                "model_name": "Keras",
                "error": f"IMAGE_MODEL_PATH does not exist: {model_path}",
            }
    try:
        from tensorflow.keras.models import load_model as keras_load_model

        model = keras_load_model(model_path)
    except Exception as exc:
        return {"model": None, "model_loaded": False, "model_name": "Keras", "error": str(exc)}
    return {"model": model, "model_loaded": True, "model_name": "Keras", "error": ""}


def _open_image(image_path: str) -> Image.Image:
    try:
        return Image.open(image_path).convert("RGB")
    except (OSError, UnidentifiedImageError, ValueError) as exc:
        raise ValueError("Invalid image file") from exc


def preprocess_image(image: Image.Image) -> np.ndarray:
    image = image.convert("RGB").resize(MODEL_INPUT_SIZE, Image.Resampling.LANCZOS)
    image_array = np.asarray(image, dtype=np.float32) / 255.0
    return np.expand_dims(image_array, axis=0)


def predict_image(image: Image.Image) -> dict:
    keras_state = load_keras_model()
    if keras_state["model_loaded"]:
        try:
            model_input = preprocess_image(image)
            print(f"[DEBUG] Keras model input_shape: {getattr(keras_state['model'], 'input_shape', None)}", flush=True)
            print(f"[DEBUG] preprocess output shape: {model_input.shape}", flush=True)
            print(f"[DEBUG] preprocess dtype: {model_input.dtype}", flush=True)
            print(
                f"[DEBUG] preprocess value range: min={float(np.min(model_input)):.6f}, max={float(np.max(model_input)):.6f}",
                flush=True,
            )
            print(
                "[DEBUG] preprocess pipeline uses PIL RGB conversion (not OpenCV BGR) and scales pixels by /255.0",
                flush=True,
            )
            raw_prediction = np.asarray(keras_state["model"].predict(model_input, verbose=0), dtype=np.float32).reshape(-1)
            print(f"[DEBUG] model.predict raw shape: {raw_prediction.shape}", flush=True)
            print(f"[DEBUG] model.predict raw values: {raw_prediction.tolist()}", flush=True)
            probability_index = int(os.getenv("MODEL_PROBABILITY_INDEX", "1")) if raw_prediction.size > 1 else 0
            if probability_index < 0 or probability_index >= raw_prediction.size:
                probability_index = 0
            print(f"[DEBUG] MODEL_PROBABILITY_INDEX: {probability_index}", flush=True)
            print(f"[DEBUG] selected output value: {float(raw_prediction[probability_index]):.8f}", flush=True)
            print(
                f"[DEBUG] MODEL_HIGH_VALUE_LABEL: {os.getenv('MODEL_HIGH_VALUE_LABEL', 'fake').strip().lower()}",
                flush=True,
            )
            fake_probability = _clamp(float(raw_prediction[probability_index]))
            print("Prediction source: model", flush=True)
            print(f"Raw prediction value: {fake_probability:.8f}", flush=True)
            return {
                "source": "model",
                "model_loaded": True,
                "model_name": keras_state["model_name"],
                "raw_prediction": raw_prediction.tolist(),
                "fake_probability": fake_probability,
                "label_scores": None,
                "labels": None,
                "fallback_reason": "",
                "reliability_score": 0.90,
            }
        except Exception as exc:
            print(f"Keras prediction error: {exc}", flush=True)

    model_state = load_model()
    if not model_state["model_loaded"]:
        print("Prediction source: fallback", flush=True)
        return {
            "source": "fallback",
            "model_loaded": False,
            "model_name": model_state["model_name"],
            "raw_prediction": None,
            "fake_probability": None,
            "fallback_reason": model_state["error"] if model_state["error"] else keras_state["error"],
            "reliability_score": 0.0,
        }

    try:
        print("Running inference...", flush=True)
        image = image.convert("RGB")

        # CLIP is used here as a balanced zero-shot ranker.
        # We compare the image against several binary real-vs-fake prompt pairs,
        # softmax each pair independently, then average the "fake" probabilities.
        pair_results = []

        with torch.no_grad():
            for prompt_pair in CLIP_PROMPT_PAIRS:
                real_prompt = prompt_pair["real"]
                fake_prompt = prompt_pair["fake"]
                inputs = model_state["processor"](
                    text=[real_prompt, fake_prompt],
                    images=image,
                    return_tensors="pt",
                    padding=True,
                )
                inputs = {
                    key: value.to(model_state["device"]) if hasattr(value, "to") else value
                    for key, value in inputs.items()
                }
                outputs = model_state["model"](**inputs)
                logits = outputs.logits_per_image[0]
                probabilities = torch.softmax(logits, dim=0).detach().cpu().tolist()
                pair_results.append(
                    {
                        "real_prompt": real_prompt,
                        "fake_prompt": fake_prompt,
                        "real_probability": float(probabilities[0]),
                        "fake_probability": float(probabilities[1]),
                    }
                )

        fake_probability = _clamp(
            float(np.mean([pair["fake_probability"] for pair in pair_results]))
        )
        label_scores = {
            f"pair_{index + 1}": {
                "real_prompt": pair["real_prompt"],
                "fake_prompt": pair["fake_prompt"],
                "real_probability": pair["real_probability"],
                "fake_probability": pair["fake_probability"],
            }
            for index, pair in enumerate(pair_results)
        }
    except Exception as exc:
        print("Prediction source: fallback", flush=True)
        print(f"Model prediction error: {exc}", flush=True)
        return {
            "source": "fallback",
            "model_loaded": False,
            "model_name": model_state["model_name"],
            "raw_prediction": None,
            "fake_probability": None,
            "fallback_reason": f"model prediction failed: {exc}",
            "reliability_score": 0.0,
        }

    print("Prediction source: model", flush=True)
    print(f"Raw prediction value: {fake_probability:.8f}", flush=True)

    return {
        "source": "model",
        "model_loaded": True,
        "model_name": model_state["model_name"],
        "raw_prediction": label_scores,
        "fake_probability": fake_probability,
        "label_scores": label_scores,
        "labels": [dict(prompt_pair) for prompt_pair in CLIP_PROMPT_PAIRS],
        "fallback_reason": "",
        "reliability_score": 0.82,
    }


def analyze_metadata(image_path: str) -> dict:
    try:
        image = Image.open(image_path)
        exif = image.getexif()
    except (OSError, UnidentifiedImageError, ValueError):
        return {
            "metadata_status": "unreadable",
            "metadata_score": 0.20,
            "fields": {},
            "flags": ["metadata_unreadable"],
        }

    if not exif:
        return {
            "metadata_status": "missing",
            "metadata_score": 0.15,
            "fields": {},
            "flags": ["exif_missing"],
        }

    fields = {}
    for tag_id, value in exif.items():
        tag_name = ExifTags.TAGS.get(tag_id, str(tag_id))
        fields[tag_name] = str(value)[:300]

    metadata_text = " ".join(fields.values()).lower()
    generated_markers = ["stable diffusion", "midjourney", "dall-e", "dalle", "ai generated", "comfyui", "automatic1111"]
    editing_markers = ["photoshop", "lightroom", "gimp", "canva"]

    flags = []
    metadata_score = 0.0
    if any(marker in metadata_text for marker in generated_markers):
        flags.append("ai_generator_metadata")
        metadata_score = max(metadata_score, 0.85)
    if any(marker in metadata_text for marker in editing_markers):
        flags.append("editing_software_metadata")
        metadata_score = max(metadata_score, 0.35)

    return {
        "metadata_status": "suspicious" if flags else "present",
        "metadata_score": metadata_score,
        "field_count": len(fields),
        "fields": fields,
        "flags": flags,
    }


def analyze_heuristics(image: Image.Image) -> dict:
    rgb = np.asarray(image.convert("RGB"), dtype=np.float32)
    gray = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    noise = float(np.std(gray - blur))

    height, width = gray.shape
    dct_gray = gray[: height - (height % 2), : width - (width % 2)]
    if dct_gray.size == 0:
        raise ValueError("Image is too small to analyze")

    dct = cv2.dct(dct_gray / 255.0)
    high_freq = dct[32:, 32:]
    high_frequency_energy = float(np.mean(np.abs(high_freq))) if high_freq.size else 0.0
    channel_std = float(np.std(rgb[:, :, 0]))

    heuristic_score = 0.0
    if noise < 2.5:
        heuristic_score += 0.35
    if high_frequency_energy < 0.001:
        heuristic_score += 0.35
    if channel_std < 30:
        heuristic_score += 0.30

    return {
        "heuristic_score": _clamp(heuristic_score),
        "noise": noise,
        "dct_high_freq_energy": high_frequency_energy,
        "channel_std": channel_std,
    }


def fuse_results(model_result: dict, metadata_result: dict, heuristic_result: dict) -> dict:
    source = model_result["source"]
    model_loaded = bool(model_result["model_loaded"])
    metadata_score = metadata_result["metadata_score"]
    heuristic_score = heuristic_result["heuristic_score"]

    if model_loaded:
        model_score = model_result["fake_probability"]
        metadata_plus_heuristics_score = _clamp((metadata_score * 0.70) + (heuristic_score * 0.30))
        final_fake_score = _clamp((model_score * 0.80) + (metadata_plus_heuristics_score * 0.20))
        reliability_score = _clamp(0.86 + (0.06 if metadata_result["metadata_status"] == "present" else 0.0))
    else:
        model_score = None
        final_fake_score = _clamp((metadata_score * 0.50) + (heuristic_score * 0.50))
        reliability_score = 0.25

    prediction = _classify_fake_score(final_fake_score, model_loaded)
    confidence = _prediction_confidence(final_fake_score, prediction, source)

    if source == "fallback":
        confidence = min(confidence, MAX_FALLBACK_CONFIDENCE)

    print(f"Final fake score: {final_fake_score:.8f}", flush=True)
    print(f"Final label: {prediction}", flush=True)

    return {
        "prediction": prediction,
        "confidence": _percent(confidence),
        "source": source,
        "model_loaded": model_loaded,
        "reliability_score": round(reliability_score, 4),
        "fake_probability": final_fake_score,
        "metadata_status": metadata_result["metadata_status"],
        "risk_level": _risk_level(final_fake_score),
        "risk_score": _to_risk_score(final_fake_score),
        "verdict": prediction if prediction == "Uncertain" else prediction.upper(),
        "details": {
            "fake_probability": final_fake_score,
            "model_score": model_score,
            "metadata_score": metadata_score,
            "heuristic_score": heuristic_score,
            "metadata_status": metadata_result["metadata_status"],
            "model": model_result,
            "metadata": metadata_result,
            "heuristics": heuristic_result,
            "fusion": {
                "model_weight": 0.80 if model_loaded else 0.0,
                "metadata_plus_heuristics_weight": 0.20 if model_loaded else 1.0,
                "metadata_weight_inside_secondary_score": 0.70,
                "heuristic_weight_inside_secondary_score": 0.30,
                "final_fake_score": final_fake_score,
            },
        },
    }


def _format_image_result(fused: dict) -> dict:
    explanation = fused.get("gemini_explanation", "Explanation unavailable")
    explanation_source = "gemini" if explanation != "Explanation unavailable" else "unavailable"
    score_source = "clip_model" if fused["model_loaded"] else "heuristic"

    return {
        "model": "CLIP",
        "type": "image",
        "prediction": fused["prediction"],
        "confidence": fused["confidence"],
        "source": fused["source"],
        "model_loaded": fused["model_loaded"],
        "reliability_score": fused["reliability_score"],
        "metadata_status": fused["metadata_status"],
        "risk_level": fused["risk_level"],
        "details": fused["details"],
        "risk_score": fused["risk_score"],
        "verdict": fused["verdict"],
        "signals": {
            "fake_score": fused["fake_probability"],
            "source": fused["source"],
            "model_loaded": fused["model_loaded"],
            "score_source": score_source,
            "explanation_source": explanation_source,
            "gemini_explanation": explanation,
            "reliability_score": fused["reliability_score"],
            "metadata_status": fused["metadata_status"],
            "model_score": fused["details"]["model_score"],
            "metadata_score": fused["details"]["metadata_score"],
            "heuristic_score": fused["details"]["heuristic_score"],
        },
    }


def analyze_image(image_path: str) -> dict:
    image = _open_image(image_path)
    model_result = predict_image(image)
    metadata_result = analyze_metadata(image_path)
    heuristic_result = analyze_heuristics(image)
    model_loaded = bool(model_result["model_loaded"])
    fake_score = model_result["fake_probability"] if model_loaded else heuristic_result["heuristic_score"]
    score_source = "clip_model" if model_loaded else "heuristic"
    prediction = _classify_fake_score(fake_score, model_loaded)
    confidence = _prediction_confidence(fake_score, prediction, model_result["source"])

    if model_result["source"] == "fallback":
        confidence = min(confidence, MAX_FALLBACK_CONFIDENCE)

    gemini_explanation = _generate_gemini_image_explanation(image, fake_score)

    print(f"Final fake score: {fake_score:.8f}", flush=True)
    print(f"Final label: {prediction}", flush=True)

    fused = {
        "prediction": prediction,
        "confidence": _percent(confidence),
        "source": model_result["source"],
        "model_loaded": model_loaded,
        "reliability_score": round(model_result["reliability_score"] if model_loaded else 0.25, 4),
        "fake_probability": fake_score,
        "metadata_status": metadata_result["metadata_status"],
        "risk_level": _risk_level(fake_score),
        "risk_score": _to_risk_score(fake_score),
        "verdict": prediction if prediction == "Uncertain" else prediction.upper(),
        "gemini_explanation": gemini_explanation,
        "details": {
            "fake_probability": fake_score,
            "model_score": model_result["fake_probability"],
            "metadata_score": metadata_result["metadata_score"],
            "heuristic_score": heuristic_result["heuristic_score"],
            "metadata_status": metadata_result["metadata_status"],
            "score_source": score_source,
            "gemini": {
                "model": GEMINI_MODEL_NAME,
                "explanation": gemini_explanation,
            },
            "clip": {
                "model": model_result.get("model_name", CLIP_MODEL_NAME),
                "labels": model_result.get("labels", [dict(prompt_pair) for prompt_pair in CLIP_PROMPT_PAIRS]),
                "label_scores": model_result.get("label_scores"),
            },
            "model": model_result,
            "metadata": metadata_result,
            "heuristics": heuristic_result,
        },
    }
    return _format_image_result(fused)


def _finalize_fallback_result(asset_type: str, fake_score: float, details: dict, reliability_score: float) -> dict:
    fake_score = _clamp(fake_score)
    confidence = min(reliability_score, MAX_FALLBACK_CONFIDENCE)

    print(f"Final fake score: {fake_score:.8f}", flush=True)
    print("Prediction source: fallback", flush=True)
    print("Final label: Uncertain", flush=True)

    return {
        "model": "CLIP",
        "type": asset_type,
        "prediction": "Uncertain",
        "confidence": _percent(confidence),
        "source": "fallback",
        "model_loaded": False,
        "reliability_score": round(_clamp(reliability_score), 4),
        "metadata_status": details.get("metadata_status", "not_applicable"),
        "risk_level": _risk_level(fake_score),
        "details": details,
        "risk_score": _to_risk_score(fake_score),
        "verdict": "Uncertain",
        "signals": {
            "fake_score": fake_score,
            "source": "fallback",
            "model_loaded": False,
            "reliability_score": round(_clamp(reliability_score), 4),
            "risk_level": _risk_level(fake_score),
            "metadata_status": details.get("metadata_status", "not_applicable"),
        },
    }


def _extract_document_text(document_path: str) -> dict:
    with open(document_path, "rb") as document_file:
        raw_bytes = document_file.read(MAX_DOCUMENT_BYTES + 1)

    truncated = len(raw_bytes) > MAX_DOCUMENT_BYTES
    raw_bytes = raw_bytes[:MAX_DOCUMENT_BYTES]

    if not raw_bytes:
        raise ValueError("Document is empty")

    if raw_bytes.startswith(b"%PDF"):
        text = raw_bytes.decode("latin-1", errors="ignore")
        text = re.sub(r"[^A-Za-z0-9.,!?;:'\"()\\s-]+", " ", text)
        extraction_method = "basic_pdf_text_scan"
    else:
        text = raw_bytes.decode("utf-8", errors="ignore")
        if not text.strip():
            text = raw_bytes.decode("latin-1", errors="ignore")
        extraction_method = "plain_text_decode"

    text = re.sub(r"\s+", " ", text).strip()
    return {"text": text, "byte_count": len(raw_bytes), "truncated": truncated, "extraction_method": extraction_method}


def _document_text_analysis(text: str) -> dict:
    if not text:
        raise ValueError("No readable document text found")

    words = re.findall(r"[A-Za-z0-9']+", text.lower())
    sentences = [sentence.strip() for sentence in re.split(r"[.!?]+", text) if sentence.strip()]
    word_count = len(words)
    unique_words = len(set(words))
    unique_word_ratio = unique_words / word_count if word_count else 0.0
    repeated_words = sum(count - 1 for count in Counter(words).values() if count > 3)
    repetition_ratio = repeated_words / word_count if word_count else 0.0
    sentence_lengths = [len(re.findall(r"[A-Za-z0-9']+", sentence)) for sentence in sentences]
    avg_sentence_length = float(np.mean(sentence_lengths)) if sentence_lengths else 0.0
    sentence_length_std = float(np.std(sentence_lengths)) if sentence_lengths else 0.0
    repeated_phrases = Counter(" ".join(words[index : index + 4]) for index in range(max(0, len(words) - 3)))
    repeated_phrase_count = sum(1 for count in repeated_phrases.values() if count >= 3)

    unnatural_patterns = []
    if word_count < 40:
        unnatural_patterns.append("too_short_for_reliable_detection")
    if word_count >= 80 and unique_word_ratio < 0.35:
        unnatural_patterns.append("low_vocabulary_diversity")
    if repetition_ratio > 0.18:
        unnatural_patterns.append("high_word_repetition")
    if repeated_phrase_count > 2:
        unnatural_patterns.append("repeated_phrase_blocks")
    if len(sentences) >= 5 and sentence_length_std < 3:
        unnatural_patterns.append("overly_uniform_sentence_lengths")

    fake_score = 0.0
    fake_score += 0.20 if word_count < 40 else 0.0
    fake_score += 0.30 if unique_word_ratio < 0.35 and word_count >= 80 else 0.0
    fake_score += min(repetition_ratio * 1.4, 0.30)
    fake_score += min(repeated_phrase_count * 0.08, 0.20)
    fake_score += 0.15 if len(sentences) >= 5 and sentence_length_std < 3 else 0.0

    return {
        "fake_probability": _clamp(fake_score),
        "metrics": {
            "character_count": len(text),
            "word_count": word_count,
            "sentence_count": len(sentences),
            "unique_word_ratio": unique_word_ratio,
            "repetition_ratio": repetition_ratio,
            "avg_sentence_length": avg_sentence_length,
            "sentence_length_std": sentence_length_std,
            "repeated_phrase_count": repeated_phrase_count,
        },
        "unnatural_patterns": unnatural_patterns,
    }


def analyze_document(document_path: str) -> dict:
    extracted = _extract_document_text(document_path)
    gemini_result = _analyze_document_with_gemini(extracted["text"], extracted)
    if gemini_result:
        return gemini_result

    text_analysis = _document_text_analysis(extracted["text"])
    details = {
        "fake_probability": text_analysis["fake_probability"],
        "metadata_status": "not_applicable",
        "fallback_reason": "document ML detector is not configured; using local text heuristics",
        "metadata": {
            "byte_count": extracted["byte_count"],
            "truncated": extracted["truncated"],
            "extraction_method": extracted["extraction_method"],
        },
        "text_analysis": text_analysis,
        "external_api": {
            "enabled": False,
            "provider": None,
            "score": None,
            "note": "Hook external AI document detection APIs here.",
            "text_preview_chars": min(len(extracted["text"]), 500),
        },
    }
    result = _finalize_fallback_result("document", text_analysis["fake_probability"], details, 0.40)
    result["signals"].update(text_analysis["metrics"])
    return result


def _sample_video_frames(video_path: str) -> dict:
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError(f"Could not open video: {video_path}")

    max_frames = max(1, int(os.getenv("VIDEO_MAX_FRAMES", "12")))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    fps = float(cap.get(cv2.CAP_PROP_FPS) or 0.0)

    if total_frames > 0:
        frame_indexes = np.linspace(0, max(total_frames - 1, 0), num=min(max_frames, total_frames), dtype=int)
    else:
        frame_indexes = np.arange(max_frames, dtype=int) * 30

    frames = []
    try:
        for frame_index in frame_indexes:
            cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
            ok, frame = cap.read()
            if not ok:
                continue
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frames.append({"frame_index": int(frame_index), "image": Image.fromarray(rgb_frame)})
    finally:
        cap.release()

    if not frames:
        raise ValueError("No readable video frames found")

    return {"frames": frames, "total_frames": total_frames, "fps": fps, "sampled_frames": len(frames)}


def analyze_video(video_path: str) -> dict:
    sampled = _sample_video_frames(video_path)

    frame_results = []

    for frame in sampled["frames"]:
        model_result = predict_image(frame["image"])
        heuristic_result = analyze_heuristics(frame["image"])
        frame_model_loaded = bool(model_result["model_loaded"])
        frame_score = model_result["fake_probability"] if frame_model_loaded else heuristic_result["heuristic_score"]
        frame_results.append(
            {
                "frame_index": frame["frame_index"],
                "fake_probability": frame_score,
                "score_source": "clip_model" if frame_model_loaded else "heuristic",
                "source": model_result["source"],
                "model_loaded": frame_model_loaded,
                "raw_prediction": model_result["raw_prediction"],
                "model_score": model_result["fake_probability"],
                "label_scores": model_result.get("label_scores"),
                "heuristics": heuristic_result,
                "image": frame["image"],
            }
        )

    model_frames = [frame for frame in frame_results if frame["model_loaded"]]
    frame_scores = [frame["fake_probability"] for frame in frame_results]
    aggregate_score = float(np.mean(frame_scores))
    model_loaded = bool(model_frames)
    source = "model" if model_loaded else "fallback"

    details = {
        "fake_probability": aggregate_score,
        "metadata_status": "not_applicable",
        "metadata": {
            "total_frames": sampled["total_frames"],
            "fps": sampled["fps"],
            "sampled_frames": sampled["sampled_frames"],
        },
        "frame_analysis": {
            "aggregate_score": aggregate_score,
            "model_frame_count": len(model_frames),
            "fallback_frame_count": len(frame_results) - len(model_frames),
            "min_score": float(np.min(frame_scores)),
            "max_score": float(np.max(frame_scores)),
            "score_std": float(np.std(frame_scores)),
            "frames": [
                {key: value for key, value in frame.items() if key != "image"}
                for frame in frame_results
            ],
        },
    }

    highest_risk_frame = max(frame_results, key=lambda frame: frame["fake_probability"])
    gemini_explanation = _generate_gemini_video_explanation(
        highest_risk_frame["image"], highest_risk_frame["fake_probability"]
    )
    explanation_source = "gemini" if gemini_explanation != "Explanation unavailable" else "unavailable"
    score_source = "clip_model" if model_loaded else "heuristic"

    if not model_loaded:
        result = _finalize_fallback_result("video", aggregate_score, details, 0.30)
    else:
        prediction = _classify_fake_score(aggregate_score, True)
        confidence = _prediction_confidence(aggregate_score, prediction, "model")
        result = {
            "model": "CLIP",
            "type": "video",
            "prediction": prediction,
            "confidence": _percent(confidence),
            "source": source,
            "model_loaded": True,
            "reliability_score": round(len(model_frames) / len(frame_results), 4),
            "metadata_status": "not_applicable",
            "risk_level": _risk_level(aggregate_score),
            "details": details,
            "risk_score": _to_risk_score(aggregate_score),
            "verdict": prediction if prediction == "Uncertain" else prediction.upper(),
            "signals": {
                "fake_score": aggregate_score,
                "source": source,
                "model_loaded": True,
                "score_source": "clip_model",
                "explanation_source": explanation_source,
                "gemini_explanation": gemini_explanation,
                "sampled_frames": sampled["sampled_frames"],
                "model_frame_count": len(model_frames),
                "fallback_frame_count": len(frame_results) - len(model_frames),
            },
        }

    result["details"]["gemini"] = {
        "model": GEMINI_MODEL_NAME,
        "explanation": gemini_explanation,
        "highest_risk_frame_index": highest_risk_frame["frame_index"],
        "highest_risk_frame_score": highest_risk_frame["fake_probability"],
    }
    result["details"]["clip"] = {
        "model": CLIP_MODEL_NAME,
        "labels": [dict(prompt_pair) for prompt_pair in CLIP_PROMPT_PAIRS],
        "highest_risk_frame_index": highest_risk_frame["frame_index"],
        "highest_risk_frame_label_scores": highest_risk_frame.get("label_scores"),
    }
    result["signals"].update(
        {
            "score_source": score_source,
            "explanation_source": explanation_source,
            "gemini_explanation": gemini_explanation,
            "model_loaded": model_loaded,
        }
    )

    return result


analyze_photo = analyze_image
