from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def generate_report(data: dict) -> str:
    verification_id = data.get("verification_id", "verification")
    candidate_id = data.get("candidate_id", "")
    org_id = data.get("org_id", "")
    risk_score = data.get("risk_score", 0)
    verdict = data.get("verdict", "")
    signals = data.get("signals", {}) or {}
    asset_type = data.get("asset_type", "")
    timestamp = data.get("timestamp", "")

    file_path = f"/tmp/{verification_id}.pdf"
    pdf = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4
    margin = 50
    y = height - margin

    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(margin, y, "VerifyMe — Identity Verification Report")
    y -= 18

    pdf.setStrokeColor(colors.black)
    pdf.line(margin, y, width - margin, y)
    y -= 35

    table_rows = [
        ("Candidate ID", candidate_id),
        ("Org", org_id),
        ("Date", timestamp),
        ("Asset type", asset_type),
    ]
    label_x = margin
    value_x = margin + 140
    row_height = 22

    pdf.setFont("Helvetica", 11)
    for label, value in table_rows:
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(label_x, y, str(label))
        pdf.setFont("Helvetica", 11)
        pdf.drawString(value_x, y, str(value))
        y -= row_height

    y -= 35
    verdict_color = colors.red if verdict == "LIKELY FAKE" else colors.green
    pdf.setFillColor(verdict_color)
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawCentredString(width / 2, y, str(verdict))
    pdf.setFillColor(colors.black)
    y -= 50

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(margin, y, f"Risk Score: {risk_score}/100")
    y -= 20

    bar_width = width - (margin * 2)
    bar_height = 18
    try:
        risk_value = float(risk_score)
    except (TypeError, ValueError):
        risk_value = 0

    if risk_value > 50:
        bar_color = colors.red
    elif risk_value >= 25:
        bar_color = colors.orange
    else:
        bar_color = colors.green

    pdf.setStrokeColor(colors.black)
    pdf.rect(margin, y, bar_width, bar_height, stroke=1, fill=0)
    pdf.setFillColor(bar_color)
    pdf.rect(margin, y, bar_width * max(0, min(risk_value, 100)) / 100, bar_height, stroke=0, fill=1)
    pdf.setFillColor(colors.black)
    y -= 55

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(margin, y, "Detection Signals")
    y -= 25

    pdf.setFont("Helvetica", 11)
    for key, value in signals.items():
        if y < margin + 40:
            pdf.showPage()
            y = height - margin
            pdf.setFont("Helvetica", 11)
        pdf.drawString(margin + 10, y, u"\u2022")
        pdf.drawString(margin + 28, y, f"{key}: {value}")
        y -= 18

    pdf.setFont("Helvetica", 9)
    pdf.setFillColor(colors.gray)
    pdf.drawCentredString(width / 2, margin / 2, "Generated by VerifyMe | Not legal advice | verifyme.app")

    pdf.save()
    return file_path