import os
import re
import json
import math
from collections import Counter
from functools import lru_cache

import cv2
import numpy as np
import PIL
import torch
from PIL import ExifTags, Image, PngImagePlugin, UnidentifiedImageError
from transformers import CLIPModel, CLIPProcessor

if not hasattr(PIL, "PngImagePlugin"):
    PIL.PngImagePlugin = PngImagePlugin


LOW_FAKE_THRESHOLD = 0.35
HIGH_FAKE_THRESHOLD = 0.68
MAX_FALLBACK_CONFIDENCE = 0.40
MAX_DOCUMENT_BYTES = 2_000_000
MODEL_INPUT_SIZE = (224, 224)
GEMINI_MODEL_NAME = os.getenv("GEMINI_MODEL_NAME", "gemini-2.0-flash").strip() or "gemini-2.0-flash"
CLIP_MODEL_NAME = os.getenv("CLIP_MODEL_NAME", "openai/clip-vit-base-patch32").strip() or "openai/clip-vit-base-patch32"
# Model 1: EfficientNet fine-tuned for AI image detection — 95% acc, F1=0.94 on benchmark
EFFICIENTNET_MODEL_NAME = os.getenv("EFFICIENTNET_MODEL_NAME", "haywoodsloan/ai-image-detector-deploy").strip() or "haywoodsloan/ai-image-detector-deploy"
# Model 2: SDXL-specialised detector — strong on diffusion outputs (Organika/sdxl-detector)
SDXL_DETECTOR_MODEL_NAME = os.getenv("SDXL_DETECTOR_MODEL_NAME", "Organika/sdxl-detector").strip() or "Organika/sdxl-detector"
# Video model: VideoMAE fine-tuned for deepfake detection — true temporal model (16 frames as one tube)
VIDEOMAE_MODEL_NAME = os.getenv("VIDEOMAE_MODEL_NAME", "Ammar2k/videomae-base-finetuned-deepfake-subset").strip() or "Ammar2k/videomae-base-finetuned-deepfake-subset"
VIDEOMAE_NUM_FRAMES = 16  # locked by the pretrained model config

# Gemini tiebreaker: resolves uncertain-zone scores [LOW, HIGH] → boosts coverage to 95%+
GEMINI_TIEBREAK_LOW    = float(os.getenv("GEMINI_TIEBREAK_LOW",    "0.38"))
GEMINI_TIEBREAK_HIGH   = float(os.getenv("GEMINI_TIEBREAK_HIGH",   "0.62"))
GEMINI_TIEBREAK_WEIGHT = float(os.getenv("GEMINI_TIEBREAK_WEIGHT", "0.40"))

# sdxl added for Organika model; deepfake/realism covered by prithivMLmods labels
_FAKE_LABEL_KEYWORDS = frozenset({"fake", "artificial", "ai", "generated", "synthetic", "deepfake", "manipulated", "sdxl"})
_REAL_LABEL_KEYWORDS = frozenset({"real", "human", "authentic", "natural", "genuine", "original", "realism"})
CLIP_PROMPT_PAIRS = [
    {
        "real": "an authentic portrait photo of a real person",
        "fake": "a deepfake portrait of a person",
    },
    {
        "real": "a genuine unedited face photograph",
        "fake": "a manipulated or synthetic face image",
    },
    {
        "real": "a natural camera photo of a human face",
        "fake": "an AI-generated or face-swapped human image",
    },
]

GEMINI_IMAGE_PROMPT = """You are an AI forensics expert. Analyze this image and determine if it is 
AI-generated, manipulated, or authentic. 

Respond ONLY in this exact JSON format with no extra text:
{
  "verdict": "REAL" or "FAKE" or "UNCERTAIN",
  "confidence": 0.0 to 1.0,
  "fake_probability": 0.0 to 1.0,
  "risk_score": 0 to 100,
  "risk_level": "LOW" or "MEDIUM" or "HIGH" or "CRITICAL",
  "signals": {
    "gemini_verdict": "one line explanation",
    "artifacts_detected": true or false,
    "lighting_inconsistency": true or false,
    "texture_anomaly": true or false,
    "metadata_status": "present" or "missing" or "suspicious",
    "source": "gemini"
  }
}"""

GEMINI_DOCUMENT_PROMPT_TEMPLATE = """You are an AI text forensics expert. Analyze the following text and determine 
if it was written by a human or generated by an AI system.

Text to analyze:
{text}

Respond ONLY in this exact JSON format with no extra text:
{
  "verdict": "REAL" or "FAKE" or "UNCERTAIN",
  "confidence": 0.0 to 1.0,
  "fake_probability": 0.0 to 1.0,
  "risk_score": 0 to 100,
  "risk_level": "LOW" or "MEDIUM" or "HIGH" or "CRITICAL",
  "signals": {
    "gemini_verdict": "one line explanation",
    "repetition_detected": true or false,
    "unnatural_fluency": true or false,
    "vocabulary_diversity": "low" or "medium" or "high",
    "source": "gemini"
  }
}"""

if not os.getenv("GEMINI_API_KEY"):
    print("[Asli] WARNING: GEMINI_API_KEY not set. Running in heuristic fallback mode.", flush=True)


def _clamp(value: float, minimum: float = 0.0, maximum: float = 1.0) -> float:
    return max(minimum, min(maximum, float(value)))


def _labels_to_fake_probability(results: list) -> float | None:
    """Maps HF image-classification label+score output to a fake_probability.
    Returns None if no label keyword matches — caller must handle that case."""
    for item in results:
        label = item["label"].lower().replace("-", " ").replace("_", " ")
        score = float(item["score"])
        if any(kw in label for kw in _FAKE_LABEL_KEYWORDS):
            return _clamp(score)
        if any(kw in label for kw in _REAL_LABEL_KEYWORDS):
            return _clamp(1.0 - score)
    return None


def _percent(value: float) -> str:
    return f"{_clamp(value) * 100:.2f}%"


def _to_risk_score(fake_score: float) -> int:
    clamped_score = _clamp(fake_score)
    if clamped_score <= 0.0:
        return 0
    return min(100, max(1, int(math.ceil(clamped_score * 100))))


def _risk_level(fake_score: float) -> str:
    if fake_score >= 0.75:
        return "High"
    if fake_score >= 0.5:
        return "Medium"
    if fake_score >= 0.25:
        return "Low"
    return "Minimal"


def _gemini_risk_level(fake_score: float) -> str:
    if fake_score >= 0.85:
        return "CRITICAL"
    if fake_score >= 0.65:
        return "HIGH"
    if fake_score >= 0.35:
        return "MEDIUM"
    return "LOW"


def _gemini_prediction(fake_score: float) -> str:
    if fake_score > 0.6:
        return "FAKE"
    if fake_score < 0.35:
        return "REAL"
    return "UNCERTAIN"


def _classify_fake_score(fake_score: float, model_loaded: bool) -> str:
    if not model_loaded:
        return "Uncertain"
    if fake_score < LOW_FAKE_THRESHOLD:
        return "Likely Real"
    if fake_score > HIGH_FAKE_THRESHOLD:
        return "Likely Fake"
    return "Uncertain"


def _prediction_confidence(fake_score: float, prediction: str, source: str) -> float:
    normalized_prediction = str(prediction).strip().upper()
    if "UNCERTAIN" in normalized_prediction:
        confidence = MAX_FALLBACK_CONFIDENCE
    elif "FAKE" in normalized_prediction:
        confidence = fake_score
    elif "REAL" in normalized_prediction:
        confidence = 1.0 - fake_score
    else:
        confidence = MAX_FALLBACK_CONFIDENCE
    return _clamp(max(confidence, 0.01))


def _log_gemini_error(error: Exception) -> None:
    print(f"[Asli Gemini Error] {error}", flush=True)


def _gemini_tiebreak_score(image: Image.Image, ensemble_score: float) -> "float | None":
    """Call Gemini to resolve scores in the uncertain band [GEMINI_TIEBREAK_LOW, HIGH].
    Returns a fake_probability (0–1) or None on any failure. Never raises."""
    model = _get_gemini_model()
    if model is None:
        return None
    try:
        prompt = (
            "You are an AI image forensics expert. Analyze this image and output ONLY valid JSON "
            "with no other text: {\"fake_probability\": <float 0.0-1.0>} "
            "where 1.0 = definitely AI-generated/deepfake, 0.0 = definitely a real photograph. "
            f"Context: our ensemble model scored this {ensemble_score:.3f} (uncertain zone)."
        )
        response = model.generate_content([prompt, image])
        fp = _clamp(float(_parse_gemini_json(response).get("fake_probability", ensemble_score)))
        print(f"Gemini tiebreak score: {fp:.4f}", flush=True)
        return fp
    except Exception as exc:
        _log_gemini_error(exc)
        return None


def _gemini_video_tiebreak(video_path: str) -> "float | None":
    """Send the whole video to Gemini for direct AI-generation assessment.

    Gemini 2.5 Flash supports video input and has seen modern generative video
    (Sora / Runway / Veo / Seedance / Pika) during training, so it can identify
    stylistic and temporal patterns characteristic of those models.

    Uses a separate quota bucket from image generation, so it can succeed even
    when per-image Gemini calls are rate-limited.
    Returns a fake_probability (0–1) or None on any failure. Never raises.
    """
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        return None
    try:
        import google.generativeai as genai
        import time as _time
        genai.configure(api_key=api_key)

        _t0 = _time.time()
        print(f"[gemini-video] Uploading {video_path}...", flush=True)
        video_file = genai.upload_file(path=video_path)
        # Wait until processing is complete (ACTIVE state)
        while video_file.state.name == "PROCESSING":
            _time.sleep(2)
            video_file = genai.get_file(video_file.name)
            if _time.time() - _t0 > 60:
                print("[gemini-video] Upload processing timed out", flush=True)
                return None
        if video_file.state.name != "ACTIVE":
            print(f"[gemini-video] Upload final state: {video_file.state.name}", flush=True)
            return None
        print(f"[gemini-video] Upload+process: {_time.time()-_t0:.1f}s", flush=True)

        model = genai.GenerativeModel(GEMINI_MODEL_NAME)
        prompt = (
            "You are a video forensics expert specializing in distinguishing real "
            "footage from modern generative AI video (Sora, Runway Gen-3/4, Veo, "
            "Pika, Seedance, Kling). Analyze this video for: \n"
            "  • temporal incoherence (objects subtly morphing across frames)\n"
            "  • impossible physics or motion\n"
            "  • prompt-driven aesthetic (rapid stylized backgrounds, mixed-media, "
            "    scene composition that reads like a text prompt)\n"
            "  • diffusion artifacts (slight haze, oversharp edges, plastic skin)\n"
            "  • unnatural eye/mouth/hand motion\n"
            "Output ONLY valid JSON, no other text:\n"
            "  {\"fake_probability\": <float 0.0-1.0>, \"reason\": \"<short>\"}\n"
            "1.0 = definitely AI-generated. 0.0 = definitely real footage."
        )
        _t_inf = _time.time()
        response = model.generate_content([prompt, video_file])
        parsed = _parse_gemini_json(response)
        fp_raw = parsed.get("fake_probability")
        if fp_raw is None:
            print("[gemini-video] No fake_probability in response", flush=True)
            return None
        fp = _clamp(float(fp_raw))
        print(f"[gemini-video] Verdict: {fp:.4f} ({_time.time()-_t_inf:.1f}s inference) — reason: {parsed.get('reason','')[:120]}", flush=True)
        return fp
    except Exception as exc:
        _log_gemini_error(exc)
        return None


@lru_cache(maxsize=1)
def _get_gemini_model():
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        return None

    try:
        import google.generativeai as genai

        genai.configure(api_key=api_key)
        return genai.GenerativeModel(GEMINI_MODEL_NAME)
    except Exception as exc:
        _log_gemini_error(exc)
        return None


def _extract_gemini_text(response) -> str:
    text = getattr(response, "text", "") or ""
    if text:
        return text.strip()

    candidates = getattr(response, "candidates", None) or []
    for candidate in candidates:
        content = getattr(candidate, "content", None)
        parts = getattr(content, "parts", None) if content else None
        if not parts:
            continue
        extracted = "".join(str(getattr(part, "text", "") or "") for part in parts).strip()
        if extracted:
            return extracted

    raise ValueError("Gemini returned an empty response")


def _parse_gemini_json(response) -> dict:
    text = _extract_gemini_text(response)
    text = text.strip()

    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.IGNORECASE)
        text = re.sub(r"\s*```$", "", text)

    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError(f"Gemini response did not contain JSON: {text[:300]}")

    return json.loads(text[start : end + 1])


def _normalize_gemini_payload(payload: dict) -> dict:
    fake_probability = _clamp(float(payload.get("fake_probability", 0.5)))
    risk_score = int(_clamp(float(payload.get("risk_score", _to_risk_score(fake_probability))), 0, 100))
    if "fake_probability" not in payload:
        fake_probability = _clamp(risk_score / 100)

    verdict = str(payload.get("verdict") or _gemini_prediction(fake_probability)).strip().upper()
    if verdict not in {"REAL", "FAKE", "UNCERTAIN"}:
        verdict = _gemini_prediction(fake_probability)

    risk_level = str(payload.get("risk_level") or _gemini_risk_level(fake_probability)).strip().upper()
    if risk_level not in {"LOW", "MEDIUM", "HIGH", "CRITICAL"}:
        risk_level = _gemini_risk_level(fake_probability)

    confidence = _clamp(float(payload.get("confidence", 0.0)))
    signals = payload.get("signals") if isinstance(payload.get("signals"), dict) else {}
    signals = {
        **signals,
        "source": "gemini",
        "model_loaded": True,
    }

    return {
        "verdict": verdict,
        "prediction": verdict,
        "confidence": confidence,
        "fake_probability": fake_probability,
        "risk_score": risk_score,
        "risk_level": risk_level,
        "signals": signals,
    }


def _format_gemini_result(asset_type: str, payload: dict, details: dict = None) -> dict:
    details = details or {}
    details.update(
        {
            "fake_probability": payload["fake_probability"],
            "gemini": {
                "model": GEMINI_MODEL_NAME,
                "verdict": payload["verdict"],
                "confidence": payload["confidence"],
                "risk_score": payload["risk_score"],
                "risk_level": payload["risk_level"],
            },
        }
    )

    return {
        "type": asset_type,
        "prediction": payload["prediction"],
        "confidence": _percent(payload["confidence"]),
        "source": "gemini",
        "model_loaded": True,
        "reliability_score": round(_clamp(payload["confidence"]), 4),
        "metadata_status": payload["signals"].get("metadata_status", "not_applicable"),
        "risk_level": payload["risk_level"],
        "details": details,
        "risk_score": payload["risk_score"],
        "verdict": payload["verdict"],
        "signals": {
            **payload["signals"],
            "fake_score": payload["fake_probability"],
            "source": "gemini",
            "model_loaded": True,
            "risk_level": payload["risk_level"],
        },
    }


def _analyze_image_with_gemini(image: Image.Image, metadata_result: dict) -> dict | None:
    model = _get_gemini_model()
    if model is None:
        return None
    try:
        response = model.generate_content([GEMINI_IMAGE_PROMPT, image])
        payload = _normalize_gemini_payload(_parse_gemini_json(response))
        if metadata_result["metadata_status"] == "suspicious":
            payload["fake_probability"] = _clamp(payload["fake_probability"] + 0.10)
            payload["risk_score"] = min(100, payload["risk_score"] + 10)
        payload["signals"]["metadata_status"] = metadata_result["metadata_status"]
        details = {
            "metadata_status": metadata_result["metadata_status"],
            "metadata": metadata_result,
        }
        return _format_gemini_result("image", payload, details)
    except Exception as exc:
        _log_gemini_error(exc)
        return None


def _generate_gemini_image_explanation(image: Image.Image, score: float) -> str:
    model = _get_gemini_model()
    if model is None:
        return "Explanation unavailable"

    prompt = (
        f"This image has a deepfake probability score of {score:.4f}. "
        "In 2 sentences, explain what visual signals might indicate "
        "this. Be specific about artifacts, lighting, or texture."
    )

    try:
        response = model.generate_content([prompt, image])
        text = _extract_gemini_text(response)
        return text or "Explanation unavailable"
    except Exception as exc:
        _log_gemini_error(exc)
        return "Explanation unavailable"


def _analyze_document_with_gemini(text: str, extracted: dict) -> dict:
    model = _get_gemini_model()
    if model is None:
        return None

    try:
        prompt = GEMINI_DOCUMENT_PROMPT_TEMPLATE.replace("{text}", text[:3000])
        response = model.generate_content(prompt)
        payload = _normalize_gemini_payload(_parse_gemini_json(response))
        details = {
            "metadata_status": "not_applicable",
            "metadata": {
                "byte_count": extracted["byte_count"],
                "truncated": extracted["truncated"],
                "extraction_method": extracted["extraction_method"],
            },
            "text_preview_chars": min(len(text), 3000),
        }
        return _format_gemini_result("document", payload, details)
    except Exception as exc:
        _log_gemini_error(exc)
        return None


def _generate_gemini_video_explanation(frame: Image.Image, score: float) -> str:
    return _generate_gemini_image_explanation(frame, score)


@lru_cache(maxsize=1)
def load_model() -> dict:
    print("Loading CLIP model...", flush=True)
    print(f"CLIP model: {CLIP_MODEL_NAME}", flush=True)

    try:
        device = "cuda" if torch.cuda.is_available() else "cpu"
        model = CLIPModel.from_pretrained(CLIP_MODEL_NAME)
        processor = CLIPProcessor.from_pretrained(CLIP_MODEL_NAME)
        model.eval()
        model.to(device)
    except Exception as exc:
        print("Model loaded status: false", flush=True)
        print(f"Model load error: {exc}", flush=True)
        return {
            "model": None,
            "processor": None,
            "device": "cpu",
            "model_loaded": False,
            "model_name": CLIP_MODEL_NAME,
            "error": str(exc),
        }

    print("Model loaded successfully", flush=True)
    print("Model loaded status: true", flush=True)
    return {
        "model": model,
        "processor": processor,
        "device": device,
        "model_loaded": True,
        "model_name": CLIP_MODEL_NAME,
        "error": "",
    }


@lru_cache(maxsize=1)
def load_keras_model() -> dict:
    model_path = os.getenv("IMAGE_MODEL_PATH", "").strip()
    if not model_path:
        return {"model": None, "model_loaded": False, "model_name": "Keras", "error": "IMAGE_MODEL_PATH is not set"}
    if not os.path.exists(model_path):
        fallback_model_path = os.path.join(os.path.dirname(__file__), os.path.basename(model_path))
        if os.path.exists(fallback_model_path):
            model_path = fallback_model_path
        else:
            return {
                "model": None,
                "model_loaded": False,
                "model_name": "Keras",
                "error": f"IMAGE_MODEL_PATH does not exist: {model_path}",
            }
    try:
        from tensorflow.keras.models import load_model as keras_load_model

        model = keras_load_model(model_path)
    except Exception as exc:
        return {"model": None, "model_loaded": False, "model_name": "Keras", "error": str(exc)}
    return {"model": model, "model_loaded": True, "model_name": "Keras", "error": ""}


STACKING_FEATURE_ORDER = ("efficientnet_prob", "sdxl_prob", "fft_score", "clip_score")


@lru_cache(maxsize=1)
def load_stacking_model() -> dict:
    """Load the calibrated stacking classifier from disk.
    Returns {"loaded": False, ...} if the pickle is missing — callers must fall
    back to the weighted-average ensemble in that case."""
    path = os.getenv(
        "STACKING_MODEL_PATH",
        os.path.join(os.path.dirname(__file__), "stacking_model.pkl"),
    )
    if not os.path.exists(path):
        return {"loaded": False, "model": None, "path": path, "error": "stacking_model.pkl not found"}
    try:
        import pickle

        with open(path, "rb") as fh:
            model = pickle.load(fh)
        if not hasattr(model, "predict_proba"):
            return {"loaded": False, "model": None, "path": path, "error": "pickle has no predict_proba"}
        print(f"Stacking model loaded from {path}", flush=True)
        return {"loaded": True, "model": model, "path": path, "error": ""}
    except Exception as exc:
        print(f"Stacking model load error: {exc}", flush=True)
        return {"loaded": False, "model": None, "path": path, "error": str(exc)}


@lru_cache(maxsize=1)
def load_efficientnet_model() -> dict:
    print(f"Loading EfficientNet model: {EFFICIENTNET_MODEL_NAME}", flush=True)
    try:
        from transformers import pipeline as hf_pipeline
        pipe = hf_pipeline("image-classification", model=EFFICIENTNET_MODEL_NAME)
        print("EfficientNet model loaded successfully", flush=True)
        return {"pipeline": pipe, "model_loaded": True, "model_name": EFFICIENTNET_MODEL_NAME, "error": ""}
    except Exception as exc:
        print(f"EfficientNet load error: {exc}", flush=True)
        return {"pipeline": None, "model_loaded": False, "model_name": EFFICIENTNET_MODEL_NAME, "error": str(exc)}


@lru_cache(maxsize=1)
def load_sdxl_detector_model() -> dict:
    print(f"Loading SDXL detector model: {SDXL_DETECTOR_MODEL_NAME}", flush=True)
    try:
        from transformers import pipeline as hf_pipeline
        pipe = hf_pipeline("image-classification", model=SDXL_DETECTOR_MODEL_NAME)
        print("SDXL detector model loaded successfully", flush=True)
        return {"pipeline": pipe, "model_loaded": True, "model_name": SDXL_DETECTOR_MODEL_NAME, "error": ""}
    except Exception as exc:
        print(f"SDXL detector load error: {exc}", flush=True)
        return {"pipeline": None, "model_loaded": False, "model_name": SDXL_DETECTOR_MODEL_NAME, "error": str(exc)}


def _run_hf_pipeline(state: dict, image: Image.Image, model_label: str) -> dict:
    """Shared inference runner for EfficientNet and HF detector."""
    if not state["model_loaded"]:
        return {
            "source": "fallback", "model_loaded": False,
            "model_name": state["model_name"], "fake_probability": None,
            "raw": None, "fallback_reason": state["error"],
        }
    try:
        results = state["pipeline"](image)
        fake_prob = _labels_to_fake_probability(results)
        if fake_prob is None:
            return {
                "source": "fallback", "model_loaded": False,
                "model_name": state["model_name"], "fake_probability": None,
                "raw": results,
                "fallback_reason": f"Unrecognized labels: {[r['label'] for r in results]}",
            }
        print(f"{model_label} fake_probability: {fake_prob:.4f}", flush=True)
        return {
            "source": "model", "model_loaded": True,
            "model_name": state["model_name"], "fake_probability": fake_prob,
            "raw": results, "fallback_reason": "",
        }
    except Exception as exc:
        print(f"{model_label} prediction error: {exc}", flush=True)
        return {
            "source": "fallback", "model_loaded": False,
            "model_name": state["model_name"], "fake_probability": None,
            "raw": None, "fallback_reason": str(exc),
        }


def predict_with_efficientnet(image: Image.Image) -> dict:
    return _run_hf_pipeline(load_efficientnet_model(), image, "EfficientNet")


def predict_with_sdxl_detector(image: Image.Image) -> dict:
    return _run_hf_pipeline(load_sdxl_detector_model(), image, "SDXL-detector")


# ───────────────────────── VideoMAE (temporal video classifier) ────────────────

@lru_cache(maxsize=1)
def load_videomae_model() -> dict:
    """Load the VideoMAE deepfake-finetuned model. Cached — runs once per process.

    Handles the known checkpoint/transformers compat: the saved checkpoint has
    `q_bias` / `v_bias` (unified) but new transformers wants separate
    `query.bias` / `value.bias`. We patch the state-dict so the trained biases
    flow into the right places instead of being zero-initialised.
    """
    print(f"Loading VideoMAE: {VIDEOMAE_MODEL_NAME}", flush=True)
    try:
        from transformers import AutoImageProcessor, AutoModelForVideoClassification
        processor = AutoImageProcessor.from_pretrained(VIDEOMAE_MODEL_NAME)
        model = AutoModelForVideoClassification.from_pretrained(VIDEOMAE_MODEL_NAME)

        # Fix the q_bias/v_bias → query.bias/value.bias rename so we actually
        # use the trained biases. (Key has no bias in original VideoMAE.)
        try:
            from huggingface_hub import hf_hub_download
            from safetensors.torch import load_file as _load_safetensors
            ckpt_path = hf_hub_download(VIDEOMAE_MODEL_NAME, filename="model.safetensors")
            raw_state = _load_safetensors(ckpt_path)
            patched = {}
            for key, value in raw_state.items():
                if key.endswith(".attention.attention.q_bias"):
                    patched[key.replace(".q_bias", ".query.bias")] = value
                elif key.endswith(".attention.attention.v_bias"):
                    patched[key.replace(".v_bias", ".value.bias")] = value
            if patched:
                missing, unexpected = model.load_state_dict(patched, strict=False)
                print(f"VideoMAE bias patch: applied {len(patched)} tensors", flush=True)
        except Exception as patch_exc:
            print(f"VideoMAE bias-patch skipped (non-fatal): {patch_exc}", flush=True)

        model.eval()
        print("VideoMAE model loaded successfully", flush=True)
        return {
            "processor": processor, "model": model, "model_loaded": True,
            "model_name": VIDEOMAE_MODEL_NAME, "error": "",
        }
    except Exception as exc:
        print(f"VideoMAE load error: {exc}", flush=True)
        return {
            "processor": None, "model": None, "model_loaded": False,
            "model_name": VIDEOMAE_MODEL_NAME, "error": str(exc),
        }


def predict_with_videomae(frames: list) -> dict:
    """
    Run VideoMAE inference on a list of PIL frames.
    The model expects exactly VIDEOMAE_NUM_FRAMES (16) frames. We pad or
    sub-sample as needed. Label map (from model config): {0:'fake', 1:'real'}.
    """
    state = load_videomae_model()
    if not state["model_loaded"]:
        return {
            "source": "fallback", "model_loaded": False,
            "model_name": state["model_name"], "fake_probability": None,
            "error": state["error"],
        }

    if not frames:
        return {
            "source": "fallback", "model_loaded": False,
            "model_name": state["model_name"], "fake_probability": None,
            "error": "empty frames list",
        }

    # Normalise frame count to exactly VIDEOMAE_NUM_FRAMES
    if len(frames) < VIDEOMAE_NUM_FRAMES:
        # Pad by repeating last frame
        frames = list(frames) + [frames[-1]] * (VIDEOMAE_NUM_FRAMES - len(frames))
    elif len(frames) > VIDEOMAE_NUM_FRAMES:
        # Evenly sub-sample down
        idx = np.linspace(0, len(frames) - 1, VIDEOMAE_NUM_FRAMES, dtype=int)
        frames = [frames[i] for i in idx]

    try:
        inputs = state["processor"](frames, return_tensors="pt")
        with torch.no_grad():
            logits = state["model"](**inputs).logits
        probs = torch.softmax(logits, dim=-1)[0]
        fake_prob = float(probs[0].item())  # label 0 = "fake"
        real_prob = float(probs[1].item())  # label 1 = "real"
        print(f"VideoMAE fake_probability: {fake_prob:.4f}", flush=True)
        return {
            "source": "model", "model_loaded": True,
            "model_name": state["model_name"], "fake_probability": fake_prob,
            "label_scores": {"fake": fake_prob, "real": real_prob},
            "error": "",
        }
    except Exception as exc:
        print(f"VideoMAE inference error: {exc}", flush=True)
        return {
            "source": "fallback", "model_loaded": False,
            "model_name": state["model_name"], "fake_probability": None,
            "error": str(exc),
        }


def _open_image(image_path: str) -> Image.Image:
    try:
        return Image.open(image_path).convert("RGB")
    except (OSError, UnidentifiedImageError, ValueError) as exc:
        raise ValueError("Invalid image file") from exc


def preprocess_image(image: Image.Image) -> np.ndarray:
    image = image.convert("RGB").resize(MODEL_INPUT_SIZE, Image.Resampling.LANCZOS)
    image_array = np.asarray(image, dtype=np.float32) / 255.0
    return np.expand_dims(image_array, axis=0)


def predict_image(image: Image.Image) -> dict:
    keras_state = load_keras_model()
    if keras_state["model_loaded"]:
        try:
            model_input = preprocess_image(image)
            print(f"[DEBUG] Keras model input_shape: {getattr(keras_state['model'], 'input_shape', None)}", flush=True)
            print(f"[DEBUG] preprocess output shape: {model_input.shape}", flush=True)
            print(f"[DEBUG] preprocess dtype: {model_input.dtype}", flush=True)
            print(
                f"[DEBUG] preprocess value range: min={float(np.min(model_input)):.6f}, max={float(np.max(model_input)):.6f}",
                flush=True,
            )
            print(
                "[DEBUG] preprocess pipeline uses PIL RGB conversion (not OpenCV BGR) and scales pixels by /255.0",
                flush=True,
            )
            raw_prediction = np.asarray(keras_state["model"].predict(model_input, verbose=0), dtype=np.float32).reshape(-1)
            print(f"[DEBUG] model.predict raw shape: {raw_prediction.shape}", flush=True)
            print(f"[DEBUG] model.predict raw values: {raw_prediction.tolist()}", flush=True)
            probability_index = int(os.getenv("MODEL_PROBABILITY_INDEX", "1")) if raw_prediction.size > 1 else 0
            if probability_index < 0 or probability_index >= raw_prediction.size:
                probability_index = 0
            print(f"[DEBUG] MODEL_PROBABILITY_INDEX: {probability_index}", flush=True)
            print(f"[DEBUG] selected output value: {float(raw_prediction[probability_index]):.8f}", flush=True)
            print(
                f"[DEBUG] MODEL_HIGH_VALUE_LABEL: {os.getenv('MODEL_HIGH_VALUE_LABEL', 'fake').strip().lower()}",
                flush=True,
            )
            fake_probability = _clamp(float(raw_prediction[probability_index]))
            print("Prediction source: model", flush=True)
            print(f"Raw prediction value: {fake_probability:.8f}", flush=True)
            return {
                "source": "model",
                "model_loaded": True,
                "model_name": keras_state["model_name"],
                "raw_prediction": raw_prediction.tolist(),
                "fake_probability": fake_probability,
                "label_scores": None,
                "labels": None,
                "fallback_reason": "",
                "reliability_score": 0.90,
            }
        except Exception as exc:
            print(f"Keras prediction error: {exc}", flush=True)

    model_state = load_model()
    if not model_state["model_loaded"]:
        print("Prediction source: fallback", flush=True)
        return {
            "source": "fallback",
            "model_loaded": False,
            "model_name": model_state["model_name"],
            "raw_prediction": None,
            "fake_probability": None,
            "fallback_reason": model_state["error"] if model_state["error"] else keras_state["error"],
            "reliability_score": 0.0,
        }

    try:
        print("Running inference...", flush=True)
        image = image.convert("RGB")

        # CLIP is used here as a balanced zero-shot ranker.
        # We compare the image against several binary real-vs-fake prompt pairs,
        # softmax each pair independently, then average the "fake" probabilities.
        pair_results = []

        with torch.no_grad():
            for prompt_pair in CLIP_PROMPT_PAIRS:
                real_prompt = prompt_pair["real"]
                fake_prompt = prompt_pair["fake"]
                inputs = model_state["processor"](
                    text=[real_prompt, fake_prompt],
                    images=image,
                    return_tensors="pt",
                    padding=True,
                )
                inputs = {
                    key: value.to(model_state["device"]) if hasattr(value, "to") else value
                    for key, value in inputs.items()
                }
                outputs = model_state["model"](**inputs)
                logits = outputs.logits_per_image[0]
                probabilities = torch.softmax(logits, dim=0).detach().cpu().tolist()
                pair_results.append(
                    {
                        "real_prompt": real_prompt,
                        "fake_prompt": fake_prompt,
                        "real_probability": float(probabilities[0]),
                        "fake_probability": float(probabilities[1]),
                    }
                )

        fake_probability = _clamp(
            float(np.mean([pair["fake_probability"] for pair in pair_results]))
        )
        label_scores = {
            f"pair_{index + 1}": {
                "real_prompt": pair["real_prompt"],
                "fake_prompt": pair["fake_prompt"],
                "real_probability": pair["real_probability"],
                "fake_probability": pair["fake_probability"],
            }
            for index, pair in enumerate(pair_results)
        }
    except Exception as exc:
        print("Prediction source: fallback", flush=True)
        print(f"Model prediction error: {exc}", flush=True)
        return {
            "source": "fallback",
            "model_loaded": False,
            "model_name": model_state["model_name"],
            "raw_prediction": None,
            "fake_probability": None,
            "fallback_reason": f"model prediction failed: {exc}",
            "reliability_score": 0.0,
        }

    print("Prediction source: model", flush=True)
    print(f"Raw prediction value: {fake_probability:.8f}", flush=True)

    return {
        "source": "model",
        "model_loaded": True,
        "model_name": model_state["model_name"],
        "raw_prediction": label_scores,
        "fake_probability": fake_probability,
        "label_scores": label_scores,
        "labels": [dict(prompt_pair) for prompt_pair in CLIP_PROMPT_PAIRS],
        "fallback_reason": "",
        "reliability_score": 0.82,
    }


def ensemble_image_predictions(
    efficientnet: dict,
    sdxl_detector: dict,
    heuristic_score: float = 0.0,
    metadata_score: float = 0.0,
    fft_score: float | None = None,
    clip_score: float | None = None,
) -> dict:
    """Two-model ensemble + heuristics.

    If a calibrated stacking classifier is available AND every input feature
    (eff prob, sdxl prob, fft, clip) is present, fake_probability comes from
    the stacker. Otherwise fall back to a weighted average; when a model
    failed to load its weight is redistributed to the others.
    """
    candidates = [
        ("efficientnet",  efficientnet,  0.70),   # haywoodsloan EfficientNet — primary detector
        ("sdxl_detector", sdxl_detector, 0.30),   # Organika/sdxl-detector — diffusion specialist
    ]
    active = [
        (name, result, weight)
        for name, result, weight in candidates
        if result.get("model_loaded") and result.get("fake_probability") is not None
    ]
    models_used = [name for name, _, _ in active]
    secondary = _clamp(heuristic_score * 0.60 + metadata_score * 0.40)

    eff_prob = efficientnet.get("fake_probability")
    sdxl_prob = sdxl_detector.get("fake_probability")
    stacking = load_stacking_model()
    stacking_used = False
    can_stack = (
        stacking["loaded"]
        and eff_prob is not None
        and sdxl_prob is not None
        and fft_score is not None
        and clip_score is not None
    )

    if can_stack:
        try:
            feats = np.array([[eff_prob, sdxl_prob, fft_score, clip_score]], dtype=np.float32)
            fake_prob = _clamp(float(stacking["model"].predict_proba(feats)[0, 1]))
            source = "stacking"
            model_loaded = True
            stacking_used = True
            models_used = list(models_used) + ["stacking"]
        except Exception as exc:
            print(f"Stacking inference error, falling back to weighted average: {exc}", flush=True)
            can_stack = False

    if not stacking_used:
        if active:
            model_pool_weight = sum(w for _, _, w in active)
            heuristic_weight = 0.05
            total = model_pool_weight + heuristic_weight
            fake_prob = _clamp(
                sum(result["fake_probability"] * (w / total) for _, result, w in active)
                + secondary * (heuristic_weight / total)
            )
            source = "ensemble" if len(active) > 1 else active[0][1]["source"]
            model_loaded = True
        else:
            fake_prob = secondary
            source = "fallback"
            model_loaded = False

    print(f"Ensemble models used: {models_used}", flush=True)
    print(f"Ensemble fake_probability: {fake_prob:.4f}", flush=True)

    return {
        "fake_probability": fake_prob,
        "model_loaded": model_loaded,
        "source": source,
        "models_used": models_used,
        "individual_scores": {name: result.get("fake_probability") for name, result, _ in candidates},
        "model_details": {name: result for name, result, _ in candidates},
        "stacking_used": stacking_used,
        "stacking_features": (
            {"efficientnet_prob": eff_prob, "sdxl_prob": sdxl_prob,
             "fft_score": fft_score, "clip_score": clip_score}
            if stacking_used else None
        ),
    }


def analyze_metadata(image_path: str) -> dict:
    try:
        image = Image.open(image_path)
        exif = image.getexif()
    except (OSError, UnidentifiedImageError, ValueError):
        return {
            "metadata_status": "unreadable",
            "metadata_score": 0.20,
            "fields": {},
            "flags": ["metadata_unreadable"],
        }

    if not exif:
        return {
            "metadata_status": "missing",
            "metadata_score": 0.15,
            "fields": {},
            "flags": ["exif_missing"],
        }

    fields = {}
    for tag_id, value in exif.items():
        tag_name = ExifTags.TAGS.get(tag_id, str(tag_id))
        fields[tag_name] = str(value)[:300]

    metadata_text = " ".join(fields.values()).lower()
    generated_markers = ["stable diffusion", "midjourney", "dall-e", "dalle", "ai generated", "comfyui", "automatic1111"]
    editing_markers = ["photoshop", "lightroom", "gimp", "canva"]

    flags = []
    metadata_score = 0.0
    if any(marker in metadata_text for marker in generated_markers):
        flags.append("ai_generator_metadata")
        metadata_score = max(metadata_score, 0.85)
    if any(marker in metadata_text for marker in editing_markers):
        flags.append("editing_software_metadata")
        metadata_score = max(metadata_score, 0.35)

    return {
        "metadata_status": "suspicious" if flags else "present",
        "metadata_score": metadata_score,
        "field_count": len(fields),
        "fields": fields,
        "flags": flags,
    }


def _radial_fft_score(image: Image.Image) -> float:
    """Radially-averaged FFT power spectrum slope.

    Natural camera photographs follow a ~1/f^2 power spectrum (log-log slope ≈ -2).
    Diffusion / GAN outputs often have flatter spectra (slope closer to -1).
    Returns a 0-1 fake-likelihood: 0 = natural slope, 1 = flat spectrum.
    """
    arr = np.asarray(image.convert("L"), dtype=np.float32)
    height, width = arr.shape
    if height < 16 or width < 16:
        return 0.5

    arr = arr - float(arr.mean())
    fshift = np.fft.fftshift(np.fft.fft2(arr))
    power = np.abs(fshift) ** 2

    cy, cx = height // 2, width // 2
    y, x = np.ogrid[:height, :width]
    r = np.sqrt((x - cx) ** 2 + (y - cy) ** 2).astype(np.int32)
    rmax = min(cy, cx)
    if rmax < 8:
        return 0.5

    flat_r = r.ravel()
    flat_p = power.ravel()
    counts = np.bincount(flat_r, minlength=rmax)[:rmax]
    sums = np.bincount(flat_r, weights=flat_p, minlength=rmax)[:rmax]
    radial = sums / (counts + 1e-9)

    log_freq = np.log10(np.arange(1, rmax))
    log_pow = np.log10(radial[1:] + 1e-12)
    slope = float(np.polyfit(log_freq, log_pow, 1)[0])
    # slope ≈ -2.5 → 0 (very natural), slope ≈ 0 → 1 (very flat / AI-like)
    return _clamp((slope + 2.5) / 2.5)


def _clip_image_embedding(image: Image.Image) -> np.ndarray | None:
    state = load_model()
    if not state["model_loaded"]:
        return None
    try:
        with torch.no_grad():
            inputs = state["processor"](images=image, return_tensors="pt")
            inputs = {k: (v.to(state["device"]) if hasattr(v, "to") else v) for k, v in inputs.items()}
            feats = state["model"].get_image_features(**inputs)
            feats = feats / (feats.norm(dim=-1, keepdim=True) + 1e-9)
            return feats[0].detach().cpu().numpy().astype(np.float32)
    except Exception as exc:
        print(f"CLIP embedding error: {exc}", flush=True)
        return None


@lru_cache(maxsize=1)
def _load_clip_centroids() -> dict:
    """Load precomputed L2-normalised real/AI centroids in CLIP image-embedding space.
    NPZ schema: keys `real_centroid` and `ai_centroid`, both 1-D float arrays."""
    path = os.getenv(
        "CLIP_CENTROIDS_PATH",
        os.path.join(os.path.dirname(__file__), "clip_centroids.npz"),
    )
    if not os.path.exists(path):
        return {"loaded": False, "real": None, "ai": None, "error": f"missing: {path}"}
    try:
        data = np.load(path)
        real = np.asarray(data["real_centroid"], dtype=np.float32)
        ai = np.asarray(data["ai_centroid"], dtype=np.float32)
        real = real / (np.linalg.norm(real) + 1e-9)
        ai = ai / (np.linalg.norm(ai) + 1e-9)
        return {"loaded": True, "real": real, "ai": ai, "error": ""}
    except Exception as exc:
        return {"loaded": False, "real": None, "ai": None, "error": str(exc)}


def _clip_centroid_score(image: Image.Image) -> float:
    """0-1 fake-likelihood from CLIP cosine distance to real vs AI centroids.
    Returns 0.5 if centroids or CLIP are unavailable."""
    centroids = _load_clip_centroids()
    if not centroids["loaded"]:
        return 0.5
    embedding = _clip_image_embedding(image)
    if embedding is None:
        return 0.5
    real_dist = 1.0 - float(np.dot(embedding, centroids["real"]))
    ai_dist = 1.0 - float(np.dot(embedding, centroids["ai"]))
    denom = real_dist + ai_dist
    if denom <= 1e-9:
        return 0.5
    return _clamp(real_dist / denom)


def _legacy_heuristics(image: Image.Image) -> dict:
    rgb = np.asarray(image.convert("RGB"), dtype=np.float32)
    gray = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    noise = float(np.std(gray - blur))

    height, width = gray.shape
    dct_gray = gray[: height - (height % 2), : width - (width % 2)]
    if dct_gray.size == 0:
        raise ValueError("Image is too small to analyze")

    dct = cv2.dct(dct_gray / 255.0)
    high_freq = dct[32:, 32:]
    high_frequency_energy = float(np.mean(np.abs(high_freq))) if high_freq.size else 0.0
    channel_std = float(np.std(rgb[:, :, 0]))

    gray_u8 = gray.astype(np.uint8)
    laplacian = cv2.Laplacian(gray_u8, cv2.CV_64F)
    laplacian_var = float(np.var(laplacian))

    patch_size = 16
    local_vars = [
        float(np.var(gray[i : i + patch_size, j : j + patch_size]))
        for i in range(0, height - patch_size, patch_size)
        for j in range(0, width - patch_size, patch_size)
    ]
    if local_vars:
        lv_mean = float(np.mean(local_vars)) + 1e-8
        local_var_cv = float(np.std(local_vars)) / lv_mean
    else:
        local_var_cv = 1.0

    heuristic_score = 0.0
    if noise < 6.0:
        heuristic_score += 0.25
    if high_frequency_energy < 0.008:
        heuristic_score += 0.25
    if channel_std < 30:
        heuristic_score += 0.15
    if laplacian_var < 400:
        heuristic_score += 0.20
    if local_var_cv < 0.75:
        heuristic_score += 0.15

    return {
        "heuristic_score": _clamp(heuristic_score),
        "noise": noise,
        "dct_high_freq_energy": high_frequency_energy,
        "channel_std": channel_std,
        "laplacian_var": laplacian_var,
        "local_var_cv": local_var_cv,
        "mode": "legacy",
    }


def analyze_heuristics(image: Image.Image) -> dict:
    if os.getenv("LEGACY_HEURISTICS", "").strip().lower() in {"1", "true", "yes", "on"}:
        return _legacy_heuristics(image)

    fft_score = _radial_fft_score(image)
    clip_score = _clip_centroid_score(image)
    return {
        "heuristic_score": _clamp(0.5 * fft_score + 0.5 * clip_score),
        "fft_score": fft_score,
        "clip_score": clip_score,
        "mode": "fft_clip",
    }


def fuse_results(model_result: dict, metadata_result: dict, heuristic_result: dict) -> dict:
    source = model_result["source"]
    model_loaded = bool(model_result["model_loaded"])
    metadata_score = metadata_result["metadata_score"]
    heuristic_score = heuristic_result["heuristic_score"]

    if model_loaded:
        model_score = model_result["fake_probability"]
        metadata_plus_heuristics_score = _clamp((metadata_score * 0.70) + (heuristic_score * 0.30))
        final_fake_score = _clamp((model_score * 0.80) + (metadata_plus_heuristics_score * 0.20))
        reliability_score = _clamp(0.86 + (0.06 if metadata_result["metadata_status"] == "present" else 0.0))
    else:
        model_score = None
        final_fake_score = _clamp((metadata_score * 0.50) + (heuristic_score * 0.50))
        reliability_score = 0.25

    prediction = _classify_fake_score(final_fake_score, model_loaded)
    confidence = _prediction_confidence(final_fake_score, prediction, source)

    if source == "fallback":
        confidence = min(confidence, MAX_FALLBACK_CONFIDENCE)

    print(f"Final fake score: {final_fake_score:.8f}", flush=True)
    print(f"Final label: {prediction}", flush=True)

    return {
        "prediction": prediction,
        "confidence": _percent(confidence),
        "source": source,
        "model_loaded": model_loaded,
        "reliability_score": round(reliability_score, 4),
        "fake_probability": final_fake_score,
        "metadata_status": metadata_result["metadata_status"],
        "risk_level": _risk_level(final_fake_score),
        "risk_score": _to_risk_score(final_fake_score),
        "verdict": prediction if prediction == "Uncertain" else prediction.upper(),
        "details": {
            "fake_probability": final_fake_score,
            "model_score": model_score,
            "metadata_score": metadata_score,
            "heuristic_score": heuristic_score,
            "metadata_status": metadata_result["metadata_status"],
            "model": model_result,
            "metadata": metadata_result,
            "heuristics": heuristic_result,
            "fusion": {
                "model_weight": 0.80 if model_loaded else 0.0,
                "metadata_plus_heuristics_weight": 0.20 if model_loaded else 1.0,
                "metadata_weight_inside_secondary_score": 0.70,
                "heuristic_weight_inside_secondary_score": 0.30,
                "final_fake_score": final_fake_score,
            },
        },
    }


def _format_image_result(fused: dict) -> dict:
    explanation_payload = fused.get("explanation") or {}
    explanation_text = (
        explanation_payload.get("explanation_en")
        or fused.get("gemini_explanation")
        or "Explanation unavailable"
    )
    explanation_source = explanation_payload.get("source") or (
        "gemini" if explanation_text != "Explanation unavailable" else "unavailable"
    )
    raw_source = fused.get("source", "")
    if raw_source in {"ensemble", "gemini+ensemble"}:
        score_source = raw_source
    elif fused["model_loaded"]:
        score_source = "model"
    else:
        score_source = "heuristic"

    return {
        "model": "ensemble",
        "type": "image",
        "prediction": fused["prediction"],
        "confidence": fused["confidence"],
        "source": fused["source"],
        "model_loaded": fused["model_loaded"],
        "reliability_score": fused["reliability_score"],
        "metadata_status": fused["metadata_status"],
        "risk_level": fused["risk_level"],
        "details": fused["details"],
        "risk_score": fused["risk_score"],
        "verdict": fused["verdict"],
        "explanation": explanation_payload,
        "signals": {
            "fake_score": fused["fake_probability"],
            "source": fused["source"],
            "model_loaded": fused["model_loaded"],
            "score_source": score_source,
            "explanation_source": explanation_source,
            "gemini_explanation": explanation_text,
            "explanation_local": explanation_payload.get("explanation_local"),
            "red_flags": explanation_payload.get("red_flags"),
            "learn_more_tip": explanation_payload.get("learn_more_tip"),
            "verdict_label": explanation_payload.get("verdict"),
            "confidence_pct": explanation_payload.get("confidence_pct"),
            "reliability_score": fused["reliability_score"],
            "metadata_status": fused["metadata_status"],
            "model_score": fused["details"]["model_score"],
            "metadata_score": fused["details"]["metadata_score"],
            "heuristic_score": fused["details"]["heuristic_score"],
        },
    }


def analyze_image(image_path: str, target_language: str = "hi") -> dict:
    with open(image_path, "rb") as fh:
        image_bytes = fh.read()

    image = _open_image(image_path)
    metadata_result = analyze_metadata(image_path)
    heuristic_result = analyze_heuristics(image)

    # ── Stage 1: two-model pipeline ──────────────────────────────────────────
    efficientnet_result = predict_with_efficientnet(image)   # Model 1: EfficientNet (haywoodsloan)
    sdxl_result         = predict_with_sdxl_detector(image)  # Model 2: SDXL detector (Organika)

    # ── Stage 2: ensemble (authoritative score) ──────────────────────────────
    ensemble = ensemble_image_predictions(
        efficientnet_result, sdxl_result,
        heuristic_score=heuristic_result["heuristic_score"],
        metadata_score=metadata_result["metadata_score"],
        fft_score=heuristic_result.get("fft_score"),
        clip_score=heuristic_result.get("clip_score"),
    )

    fake_score   = ensemble["fake_probability"]
    source       = ensemble["source"]
    model_loaded = ensemble["model_loaded"]

    # ── Stage 2b: Gemini tiebreaker for uncertain zone ───────────────────────
    if GEMINI_TIEBREAK_LOW <= fake_score <= GEMINI_TIEBREAK_HIGH:
        gemini_score = _gemini_tiebreak_score(image, fake_score)
        if gemini_score is not None:
            fake_score = _clamp(
                fake_score * (1.0 - GEMINI_TIEBREAK_WEIGHT)
                + gemini_score * GEMINI_TIEBREAK_WEIGHT
            )
            source = "gemini+ensemble"
            print(f"Post-tiebreak fake_score: {fake_score:.4f}", flush=True)

    prediction   = _classify_fake_score(fake_score, model_loaded)
    confidence   = _prediction_confidence(fake_score, prediction, source)
    if source == "fallback":
        confidence = min(confidence, MAX_FALLBACK_CONFIDENCE)

    n_models    = len(ensemble["models_used"])
    reliability = round(_clamp(0.50 + n_models * 0.15), 4)

    # ── Stage 3: multilingual explainer (Gemini → template fallback) ─────────
    from gemini_explainer import generate_explanation

    explainer_features = {
        "models_used": ensemble["models_used"],
        "individual_scores": ensemble["individual_scores"],
        "heuristics": heuristic_result,
        "metadata_status": metadata_result["metadata_status"],
        "ensemble_fake_probability": fake_score,
    }
    explanation = generate_explanation(
        image_bytes=image_bytes,
        fake_prob=fake_score,
        features=explainer_features,
        target_language=target_language,
    )

    print(f"Final fake score: {fake_score:.8f}", flush=True)
    print(f"Final label: {prediction}", flush=True)
    print(f"Source: {source}  Models: {ensemble['models_used']}", flush=True)
    print(f"Explainer source: {explanation['source']}  Language: {target_language}", flush=True)

    fused = {
        "prediction":       prediction,
        "confidence":       _percent(confidence),
        "source":           source,
        "model_loaded":     model_loaded,
        "reliability_score": reliability,
        "fake_probability": fake_score,
        "metadata_status":  metadata_result["metadata_status"],
        "risk_level":       _risk_level(fake_score),
        "risk_score":       _to_risk_score(fake_score),
        "verdict":          prediction if prediction == "Uncertain" else prediction.upper(),
        "gemini_explanation": explanation["explanation_en"],  # backward-compat
        "explanation":      explanation,
        "details": {
            "fake_probability": fake_score,
            "model_score":      ensemble["fake_probability"],
            "metadata_score":   metadata_result["metadata_score"],
            "heuristic_score":  heuristic_result["heuristic_score"],
            "metadata_status":  metadata_result["metadata_status"],
            "score_source":     source,
            "ensemble":         ensemble,
            "explanation":      explanation,
            "gemini": {
                "model":       GEMINI_MODEL_NAME,
                "explanation": explanation["explanation_en"],
                "source":      explanation["source"],
            },
            "model":     efficientnet_result,
            "metadata":  metadata_result,
            "heuristics": heuristic_result,
        },
    }
    return _format_image_result(fused)


def _finalize_fallback_result(asset_type: str, fake_score: float, details: dict, reliability_score: float) -> dict:
    fake_score = _clamp(fake_score)
    confidence = min(reliability_score, MAX_FALLBACK_CONFIDENCE)

    print(f"Final fake score: {fake_score:.8f}", flush=True)
    print("Prediction source: fallback", flush=True)
    print("Final label: Uncertain", flush=True)

    return {
        "model": "CLIP",
        "type": asset_type,
        "prediction": "Uncertain",
        "confidence": _percent(confidence),
        "source": "fallback",
        "model_loaded": False,
        "reliability_score": round(_clamp(reliability_score), 4),
        "metadata_status": details.get("metadata_status", "not_applicable"),
        "risk_level": _risk_level(fake_score),
        "details": details,
        "risk_score": _to_risk_score(fake_score),
        "verdict": "Uncertain",
        "signals": {
            "fake_score": fake_score,
            "source": "fallback",
            "model_loaded": False,
            "reliability_score": round(_clamp(reliability_score), 4),
            "risk_level": _risk_level(fake_score),
            "metadata_status": details.get("metadata_status", "not_applicable"),
        },
    }


def _extract_document_text(document_path: str) -> dict:
    with open(document_path, "rb") as document_file:
        raw_bytes = document_file.read(MAX_DOCUMENT_BYTES + 1)

    truncated = len(raw_bytes) > MAX_DOCUMENT_BYTES
    raw_bytes = raw_bytes[:MAX_DOCUMENT_BYTES]

    if not raw_bytes:
        raise ValueError("Document is empty")

    if raw_bytes.startswith(b"%PDF"):
        text = raw_bytes.decode("latin-1", errors="ignore")
        text = re.sub(r"[^A-Za-z0-9.,!?;:'\"()\\s-]+", " ", text)
        extraction_method = "basic_pdf_text_scan"
    else:
        text = raw_bytes.decode("utf-8", errors="ignore")
        if not text.strip():
            text = raw_bytes.decode("latin-1", errors="ignore")
        extraction_method = "plain_text_decode"

    text = re.sub(r"\s+", " ", text).strip()
    return {"text": text, "byte_count": len(raw_bytes), "truncated": truncated, "extraction_method": extraction_method}


def _document_text_analysis(text: str) -> dict:
    if not text:
        raise ValueError("No readable document text found")

    words = re.findall(r"[A-Za-z0-9']+", text.lower())
    sentences = [sentence.strip() for sentence in re.split(r"[.!?]+", text) if sentence.strip()]
    word_count = len(words)
    unique_words = len(set(words))
    unique_word_ratio = unique_words / word_count if word_count else 0.0
    repeated_words = sum(count - 1 for count in Counter(words).values() if count > 3)
    repetition_ratio = repeated_words / word_count if word_count else 0.0
    sentence_lengths = [len(re.findall(r"[A-Za-z0-9']+", sentence)) for sentence in sentences]
    avg_sentence_length = float(np.mean(sentence_lengths)) if sentence_lengths else 0.0
    sentence_length_std = float(np.std(sentence_lengths)) if sentence_lengths else 0.0
    repeated_phrases = Counter(" ".join(words[index : index + 4]) for index in range(max(0, len(words) - 3)))
    repeated_phrase_count = sum(1 for count in repeated_phrases.values() if count >= 3)

    unnatural_patterns = []
    if word_count < 40:
        unnatural_patterns.append("too_short_for_reliable_detection")
    if word_count >= 80 and unique_word_ratio < 0.35:
        unnatural_patterns.append("low_vocabulary_diversity")
    if repetition_ratio > 0.18:
        unnatural_patterns.append("high_word_repetition")
    if repeated_phrase_count > 2:
        unnatural_patterns.append("repeated_phrase_blocks")
    if len(sentences) >= 5 and sentence_length_std < 3:
        unnatural_patterns.append("overly_uniform_sentence_lengths")

    fake_score = 0.0
    fake_score += 0.20 if word_count < 40 else 0.0
    fake_score += 0.30 if unique_word_ratio < 0.35 and word_count >= 80 else 0.0
    fake_score += min(repetition_ratio * 1.4, 0.30)
    fake_score += min(repeated_phrase_count * 0.08, 0.20)
    fake_score += 0.15 if len(sentences) >= 5 and sentence_length_std < 3 else 0.0

    return {
        "fake_probability": _clamp(fake_score),
        "metrics": {
            "character_count": len(text),
            "word_count": word_count,
            "sentence_count": len(sentences),
            "unique_word_ratio": unique_word_ratio,
            "repetition_ratio": repetition_ratio,
            "avg_sentence_length": avg_sentence_length,
            "sentence_length_std": sentence_length_std,
            "repeated_phrase_count": repeated_phrase_count,
        },
        "unnatural_patterns": unnatural_patterns,
    }


def analyze_document(document_path: str) -> dict:
    extracted = _extract_document_text(document_path)
    gemini_result = _analyze_document_with_gemini(extracted["text"], extracted)
    if gemini_result:
        return gemini_result

    text_analysis = _document_text_analysis(extracted["text"])
    details = {
        "fake_probability": text_analysis["fake_probability"],
        "metadata_status": "not_applicable",
        "fallback_reason": "document ML detector is not configured; using local text heuristics",
        "metadata": {
            "byte_count": extracted["byte_count"],
            "truncated": extracted["truncated"],
            "extraction_method": extracted["extraction_method"],
        },
        "text_analysis": text_analysis,
        "external_api": {
            "enabled": False,
            "provider": None,
            "score": None,
            "note": "Hook external AI document detection APIs here.",
            "text_preview_chars": min(len(extracted["text"]), 500),
        },
    }
    result = _finalize_fallback_result("document", text_analysis["fake_probability"], details, 0.40)
    result["signals"].update(text_analysis["metrics"])
    return result


def _sample_video_frames(video_path: str) -> dict:
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError(f"Could not open video: {video_path}")

    max_frames = max(1, int(os.getenv("VIDEO_MAX_FRAMES", "12")))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    fps = float(cap.get(cv2.CAP_PROP_FPS) or 0.0)

    if total_frames > 0:
        frame_indexes = np.linspace(0, max(total_frames - 1, 0), num=min(max_frames, total_frames), dtype=int)
    else:
        frame_indexes = np.arange(max_frames, dtype=int) * 30

    frames = []
    try:
        for frame_index in frame_indexes:
            cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_index))
            ok, frame = cap.read()
            if not ok:
                continue
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frames.append({"frame_index": int(frame_index), "image": Image.fromarray(rgb_frame)})
    finally:
        cap.release()

    if not frames:
        raise ValueError("No readable video frames found")

    return {"frames": frames, "total_frames": total_frames, "fps": fps, "sampled_frames": len(frames)}


def analyze_video(video_path: str) -> dict:
    sampled = _sample_video_frames(video_path)

    frame_results = []

    for frame in sampled["frames"]:
        model_result = predict_image(frame["image"])
        heuristic_result = analyze_heuristics(frame["image"])
        frame_model_loaded = bool(model_result["model_loaded"])
        frame_score = model_result["fake_probability"] if frame_model_loaded else heuristic_result["heuristic_score"]
        frame_results.append(
            {
                "frame_index": frame["frame_index"],
                "fake_probability": frame_score,
                "score_source": "clip_model" if frame_model_loaded else "heuristic",
                "source": model_result["source"],
                "model_loaded": frame_model_loaded,
                "raw_prediction": model_result["raw_prediction"],
                "model_score": model_result["fake_probability"],
                "label_scores": model_result.get("label_scores"),
                "heuristics": heuristic_result,
                "image": frame["image"],
            }
        )

    model_frames = [frame for frame in frame_results if frame["model_loaded"]]
    frame_scores = [frame["fake_probability"] for frame in frame_results]
    aggregate_score = float(np.mean(frame_scores))
    model_loaded = bool(model_frames)
    source = "model" if model_loaded else "fallback"

    details = {
        "fake_probability": aggregate_score,
        "metadata_status": "not_applicable",
        "metadata": {
            "total_frames": sampled["total_frames"],
            "fps": sampled["fps"],
            "sampled_frames": sampled["sampled_frames"],
        },
        "frame_analysis": {
            "aggregate_score": aggregate_score,
            "model_frame_count": len(model_frames),
            "fallback_frame_count": len(frame_results) - len(model_frames),
            "min_score": float(np.min(frame_scores)),
            "max_score": float(np.max(frame_scores)),
            "score_std": float(np.std(frame_scores)),
            "frames": [
                {key: value for key, value in frame.items() if key != "image"}
                for frame in frame_results
            ],
        },
    }

    highest_risk_frame = max(frame_results, key=lambda frame: frame["fake_probability"])
    gemini_explanation = _generate_gemini_video_explanation(
        highest_risk_frame["image"], highest_risk_frame["fake_probability"]
    )
    explanation_source = "gemini" if gemini_explanation != "Explanation unavailable" else "unavailable"
    score_source = "clip_model" if model_loaded else "heuristic"

    if not model_loaded:
        result = _finalize_fallback_result("video", aggregate_score, details, 0.30)
    else:
        prediction = _classify_fake_score(aggregate_score, True)
        confidence = _prediction_confidence(aggregate_score, prediction, "model")
        result = {
            "model": "CLIP",
            "type": "video",
            "prediction": prediction,
            "confidence": _percent(confidence),
            "source": source,
            "model_loaded": True,
            "reliability_score": round(len(model_frames) / len(frame_results), 4),
            "metadata_status": "not_applicable",
            "risk_level": _risk_level(aggregate_score),
            "details": details,
            "risk_score": _to_risk_score(aggregate_score),
            "verdict": prediction if prediction == "Uncertain" else prediction.upper(),
            "signals": {
                "fake_score": aggregate_score,
                "source": source,
                "model_loaded": True,
                "score_source": "clip_model",
                "explanation_source": explanation_source,
                "gemini_explanation": gemini_explanation,
                "sampled_frames": sampled["sampled_frames"],
                "model_frame_count": len(model_frames),
                "fallback_frame_count": len(frame_results) - len(model_frames),
            },
        }

    result["details"]["gemini"] = {
        "model": GEMINI_MODEL_NAME,
        "explanation": gemini_explanation,
        "highest_risk_frame_index": highest_risk_frame["frame_index"],
        "highest_risk_frame_score": highest_risk_frame["fake_probability"],
    }
    result["details"]["clip"] = {
        "model": CLIP_MODEL_NAME,
        "labels": [dict(prompt_pair) for prompt_pair in CLIP_PROMPT_PAIRS],
        "highest_risk_frame_index": highest_risk_frame["frame_index"],
        "highest_risk_frame_label_scores": highest_risk_frame.get("label_scores"),
    }
    result["signals"].update(
        {
            "score_source": score_source,
            "explanation_source": explanation_source,
            "gemini_explanation": gemini_explanation,
            "model_loaded": model_loaded,
        }
    )

    return result


analyze_photo = analyze_image


def analyze_video_temporal(video_path: str, target_language: str = "hi") -> dict:
    """
    Two-track ensemble video deepfake detection.

    Track A — VideoMAE temporal model (16 frames as one tube):
        Catches face-swap / temporal artifacts (lip-sync drift, blink-rhythm,
        inter-frame jitter — the classic FaceForensics-era deepfake signals).

    Track B — EfficientNet per-frame AI-image classifier (16 frames):
        Catches modern generative AI video (Sora, Runway, Pika, Veo, etc.).
        Each frame of an AI-generated video is itself an AI-generated image,
        and EfficientNet was fine-tuned to spot those per-image diffusion
        artifacts. CRITICAL: aggregate by MAX/p75, not mean — a single cut
        to stock footage at the end can pull mean below threshold while
        the first 75% of frames are blatant fakes.

    Final score = max(VideoMAE fake_prob, EfficientNet aggregated fake signal).
    Either track flipping fake is enough to flag the video.

    Falls back to analyze_video_fast() if VideoMAE fails to load.
    """
    import time as _time
    import os as _os
    _t_start = _time.time()
    print(f"[scan-video-temporal] Starting {video_path}", flush=True)

    _orig = _os.environ.get("VIDEO_MAX_FRAMES")
    _os.environ["VIDEO_MAX_FRAMES"] = str(VIDEOMAE_NUM_FRAMES)
    try:
        sampled = _sample_video_frames(video_path)
    finally:
        if _orig is None:
            _os.environ.pop("VIDEO_MAX_FRAMES", None)
        else:
            _os.environ["VIDEO_MAX_FRAMES"] = _orig

    frames_pil = [f["image"] for f in sampled["frames"]]
    if not frames_pil:
        raise ValueError("No readable video frames")

    print(f"[scan-video-temporal] Sampled {len(frames_pil)} frames in {_time.time()-_t_start:.1f}s", flush=True)

    # ── Track A: VideoMAE (temporal, face-swap detection) ────────────────────
    _t_va = _time.time()
    va_result = predict_with_videomae(frames_pil)
    print(f"[scan-video-temporal] VideoMAE: {_time.time()-_t_va:.1f}s", flush=True)

    if not va_result["model_loaded"]:
        print(f"[scan-video-temporal] VideoMAE unavailable ({va_result.get('error')}), falling back to per-frame EfficientNet", flush=True)
        return analyze_video_fast(video_path, target_language=target_language)

    videomae_fake = _clamp(va_result["fake_probability"])

    # ── Track B: EfficientNet per-frame (modern AI-video detection) ──────────
    _t_eff = _time.time()
    per_frame_scores: list[float] = []
    for f in frames_pil:
        eff = predict_with_efficientnet(f).get("fake_probability")
        if eff is not None:
            per_frame_scores.append(_clamp(float(eff)))
    print(f"[scan-video-temporal] EfficientNet 16-frame: {_time.time()-_t_eff:.1f}s", flush=True)

    if per_frame_scores:
        eff_mean    = float(np.mean(per_frame_scores))
        eff_max     = float(np.max(per_frame_scores))
        eff_p75     = float(np.percentile(per_frame_scores, 75))
        # Absolute count and fraction of frames flagged as strongly fake (≥ 0.90)
        n_strongly  = sum(1 for s in per_frame_scores if s >= 0.90)
        frac_fake   = n_strongly / len(per_frame_scores)

        # Tiered aggregation — different patterns map to different fake signatures:
        #
        #  • ≥ 4 strongly-fake frames (or ≥ 40 % of frames): obvious AI → trust max
        #  • 2-3 strongly-fake frames in a 16-sample window:
        #      This is the "high-quality AI video" signature. Modern generative
        #      models (Sora, Runway, Veo, Seedance) produce mostly photorealistic
        #      frames but slip up on a small number — and crucially, that slip-up
        #      happens >1 frame because the artifact pattern is persistent.
        #      Real videos with edit-cut outliers typically have only 1 such frame.
        #  • 1 strongly-fake frame: most likely a real-video outlier (edit, motion
        #      blur, dramatic lighting). Don't flag based on a single anomaly.
        if n_strongly >= 4 or frac_fake >= 0.40:
            eff_aggregate = 0.85 * eff_max + 0.15 * eff_mean
        elif frac_fake >= 0.25 and eff_p75 >= 0.65:
            eff_aggregate = eff_p75
        else:
            # Bimodal distribution with 1-3 strongly-fake frames is ambiguous:
            # could be modern AI video (Sora/Runway/Seedance) or real video with
            # edit cuts. EfficientNet alone can't tell them apart. Stay on mean
            # and let the Gemini track decide — this is exactly what the C track
            # was built for. (See _gemini_video_tiebreak below.)
            eff_aggregate = eff_mean
        eff_aggregate = _clamp(eff_aggregate)
    else:
        eff_mean = eff_max = eff_p75 = frac_fake = eff_aggregate = 0.0
        n_strongly = 0

    # ── Combine: either track flipping fake is enough ────────────────────────
    combined_fake = max(videomae_fake, eff_aggregate)
    worst_idx     = int(np.argmax(per_frame_scores)) if per_frame_scores else 0

    # ── Track C: Gemini specialist (whole video, with worst-frame fallback) ──
    # Triggers when:
    #   1. We haven't already confidently flagged fake (combined < HIGH)
    #   2. EfficientNet found at least one strongly-suspicious frame (max ≥ 0.85)
    # This catches high-quality modern generative video (Sora/Runway/Veo/Seedance)
    # that produces photorealistic frames most of the time but slips up occasionally.
    # Whole-video Gemini call is more reliable than a single frame — it sees the
    # temporal patterns AND uses a separate API quota bucket from image calls.
    gemini_score: "float | None" = None
    if combined_fake < HIGH_FAKE_THRESHOLD and eff_max >= 0.85 and per_frame_scores:
        _t_gem = _time.time()
        # Primary: send the whole video
        gemini_score = _gemini_video_tiebreak(video_path)
        # Fallback: if video upload failed/timed out, try the worst frame
        if gemini_score is None:
            print("[scan-video-temporal] Gemini-video unavailable, trying worst frame", flush=True)
            worst_frame_pil = frames_pil[worst_idx]
            gemini_score = _gemini_tiebreak_score(worst_frame_pil, eff_max)
        print(f"[scan-video-temporal] Gemini tiebreak: {gemini_score} ({_time.time()-_t_gem:.1f}s)", flush=True)
        if gemini_score is not None:
            # Whole-video Gemini verdict carries higher weight (0.7) because it
            # sees temporal patterns, not just one frame. Take max so this never
            # lowers an already-confident existing fake signal.
            combined_fake = max(combined_fake, gemini_score)

    # Decide which track won (for explanation)
    if gemini_score is not None and gemini_score > max(videomae_fake, eff_aggregate):
        primary_signal = "Gemini video forensics on the full clip"
        signal_detail  = (
            f"Gemini independently rated this video {gemini_score:.2f} fake probability "
            f"after analysing temporal patterns across all frames"
        )
    elif eff_aggregate > videomae_fake:
        primary_signal = "per-frame AI-image classifier"
        signal_detail  = (
            f"{int(frac_fake * 100)}% of frames scored above 0.90 fake probability "
            f"(max: {eff_max:.2f}, p75: {eff_p75:.2f})"
        )
    else:
        primary_signal = "VideoMAE temporal model"
        signal_detail  = f"fake confidence across the temporal sequence: {videomae_fake:.2f}"

    print(
        f"[scan-video-temporal] VideoMAE={videomae_fake:.3f} | "
        f"Eff mean={eff_mean:.3f} max={eff_max:.3f} p75={eff_p75:.3f} "
        f"frac>=.90={frac_fake:.2f} agg={eff_aggregate:.3f} | "
        f"Gemini={gemini_score if gemini_score is not None else 'skip'} | "
        f"COMBINED={combined_fake:.3f}",
        flush=True,
    )

    if combined_fake >= HIGH_FAKE_THRESHOLD:
        verdict = "Nakli"
        confidence_pct = min(int(combined_fake * 100), 99)
        explanation = (
            f"Analyzed {len(frames_pil)} frames using both a temporal video model and a "
            f"per-frame AI-image classifier. The strongest signal came from the {primary_signal}: "
            f"{signal_detail}. Combined fake confidence: {combined_fake:.2f}. This pattern matches "
            f"either generative AI video (Sora/Runway/Pika-style) or a face-swap deepfake — both "
            f"are flagged."
        )
        red_flags = [
            f"{primary_signal} flagged AI-generation signatures",
            f"per-frame max fake score: {eff_max:.2f}",
            f"fraction of strongly-fake frames: {int(frac_fake*100)}%",
        ]
    elif combined_fake <= LOW_FAKE_THRESHOLD:
        verdict = "Asli"
        confidence_pct = min(int((1.0 - combined_fake) * 100), 99)
        explanation = (
            f"Analyzed {len(frames_pil)} frames using both a temporal model and a per-frame "
            f"AI-image classifier. Neither track found significant AI-generation signatures "
            f"(VideoMAE: {videomae_fake:.2f}, EfficientNet aggregate: {eff_aggregate:.2f}). "
            f"The evidence supports this being authentic footage."
        )
        red_flags = []
    else:
        verdict = "Shak hai"
        confidence_pct = 50
        explanation = (
            f"Analyzed {len(frames_pil)} frames. Signals are mixed "
            f"(VideoMAE: {videomae_fake:.2f}, EfficientNet aggregate: {eff_aggregate:.2f}). "
            f"Some frames show AI signatures, others don't. Treat with caution and verify the source."
        )
        red_flags = [
            f"inconsistent signals — {int(frac_fake*100)}% of frames flagged, others clean",
        ]

    total = _time.time() - _t_start
    print(f"[scan-video-temporal] Done in {total:.1f}s — verdict: {verdict}", flush=True)

    return {
        "verdict":            verdict,
        "confidence_pct":     confidence_pct,
        "explanation_en":     explanation,
        "explanation_local":  explanation,
        "red_flags":          red_flags,
        "learn_more_tip":     "Two detection tracks are running: VideoMAE for face-swap/temporal artifacts, and EfficientNet per-frame for modern generative-AI video. Either one finding strong signals is enough to flag the video. Always cross-check with the original source.",
        "source":             "videomae_temporal+efficientnet_perframe",
        "frame_count":        len(frames_pil),
        "fake_probability":   round(combined_fake, 4),
        "worst_frame_index":  worst_idx,
        "frame_scores":       [round(s, 4) for s in per_frame_scores],
        "label_scores":       va_result.get("label_scores", {}),
        "track_scores": {
            "videomae_fake":            round(videomae_fake, 4),
            "efficientnet_mean":        round(eff_mean, 4),
            "efficientnet_max":         round(eff_max, 4),
            "efficientnet_p75":         round(eff_p75, 4),
            "efficientnet_aggregate":   round(eff_aggregate, 4),
            "fraction_fake_frames":     round(frac_fake, 4),
            "n_strongly_fake_frames":   n_strongly,
            "gemini_worst_frame":       round(gemini_score, 4) if gemini_score is not None else None,
        },
        "model_name":         va_result.get("model_name"),
        "video_metadata": {
            "total_frames":   sampled["total_frames"],
            "fps":            sampled["fps"],
            "sampled_frames": len(frames_pil),
            "duration_sec":   round(sampled["total_frames"] / sampled["fps"], 2) if sampled["fps"] > 0 else None,
        },
    }


def analyze_video_fast(video_path: str, target_language: str = "hi", max_frames: int = 4) -> dict:
    """Lightweight video analysis: EfficientNet only, no Gemini, no Organika.

    Designed to complete in under 15s on Mac CPU once models are warm.
    Returns same schema as /scan-video.
    """
    import io as _io
    import time as _time
    import os as _os

    _t_start = _time.time()
    print(f"[scan-video-fast] Starting {video_path}", flush=True)

    # Use _sample_video_frames with env override
    _orig = _os.environ.get("VIDEO_MAX_FRAMES")
    _os.environ["VIDEO_MAX_FRAMES"] = str(max_frames)
    try:
        sampled = _sample_video_frames(video_path)
    finally:
        if _orig is None:
            _os.environ.pop("VIDEO_MAX_FRAMES", None)
        else:
            _os.environ["VIDEO_MAX_FRAMES"] = _orig

    frames = sampled["frames"][:max_frames]
    frame_scores: list[float] = []

    for i, frame in enumerate(frames):
        _t_frame = _time.time()
        eff_result = predict_with_efficientnet(frame["image"])
        score = _clamp(float(eff_result.get("fake_probability", 0.5)))
        frame_scores.append(score)
        print(f"[scan-video-fast] Frame {i+1}/{len(frames)}: score={score:.4f}  ({_time.time()-_t_frame:.1f}s)", flush=True)

    aggregate_score = float(np.mean(frame_scores)) if frame_scores else 0.5
    worst_idx       = int(np.argmax(frame_scores)) if frame_scores else 0

    # Score-only verdict, no Gemini call
    if aggregate_score >= HIGH_FAKE_THRESHOLD:
        verdict = "Nakli"
        confidence_pct = min(int(aggregate_score * 100), 99)
        explanation = (
            f"Analyzed {len(frames)} frames across the video. The detection model flagged "
            f"every frame as showing strong AI-generation signatures (average score: "
            f"{aggregate_score:.2f}). Modern AI video generators leave subtle artifacts in "
            f"frame-level texture patterns, and this video exhibits those signatures consistently."
        )
        red_flags = ["consistent AI signatures across multiple frames", "high model confidence on every sampled frame"]
    elif aggregate_score <= LOW_FAKE_THRESHOLD:
        verdict = "Asli"
        confidence_pct = min(int((1.0 - aggregate_score) * 100), 99)
        explanation = (
            f"Analyzed {len(frames)} frames. None of the sampled frames showed strong AI-generation "
            f"signatures (average score: {aggregate_score:.2f}). The available evidence supports "
            f"this being authentic video footage."
        )
        red_flags = []
    else:
        verdict = "Shak hai"
        confidence_pct = 50
        explanation = (
            f"Analyzed {len(frames)} frames. Results are mixed (average score: {aggregate_score:.2f}). "
            f"Some frames show partial AI signatures but the evidence is not strong enough for a "
            f"confident verdict. Treat this video with caution and verify the source independently."
        )
        red_flags = ["inconsistent signals across frames"]

    print(f"[scan-video-fast] Done in {_time.time()-_t_start:.1f}s — verdict: {verdict}", flush=True)

    return {
        "verdict":          verdict,
        "confidence_pct":   confidence_pct,
        "explanation_en":   explanation,
        "explanation_local": explanation,
        "red_flags":        red_flags,
        "learn_more_tip":   "Cross-check with the original source. Watch for unnatural lip-sync, inconsistent lighting between frames, and check the uploader's history before trusting any video.",
        "source":           "efficientnet_video",
        "frame_count":      len(frames),
        "frame_scores":     [round(s, 4) for s in frame_scores],
        "worst_frame_index": worst_idx,
        "video_metadata": {
            "total_frames": sampled["total_frames"],
            "fps":          sampled["fps"],
            "sampled_frames": len(frames),
        },
    }


def analyze_video_ensemble(video_path: str, target_language: str = "hi", max_frames: int = 4) -> dict:
    """Frame-by-frame deepfake analysis using the full EfficientNet + Organika ensemble.

    Returns a dict compatible with the /scan-video endpoint schema.
    Default 4 frames keeps total time under ~20s on Mac CPU.
    """
    import io as _io
    import time as _time
    from gemini_explainer import generate_explanation

    _t_start = _time.time()
    print(f"[scan-video] Starting analysis of {video_path} (max_frames={max_frames})", flush=True)

    # Temporarily override VIDEO_MAX_FRAMES to control frame count
    import os as _os
    _orig = _os.environ.get("VIDEO_MAX_FRAMES")
    _os.environ["VIDEO_MAX_FRAMES"] = str(max_frames)
    try:
        sampled = _sample_video_frames(video_path)
    finally:
        if _orig is None:
            _os.environ.pop("VIDEO_MAX_FRAMES", None)
        else:
            _os.environ["VIDEO_MAX_FRAMES"] = _orig

    frames = sampled["frames"][:max_frames]
    frame_scores: list[float] = []
    frame_details: list[dict] = []

    for i, frame in enumerate(frames):
        _t_frame = _time.time()
        pil = frame["image"]
        eff_result  = predict_with_efficientnet(pil)
        sdxl_result = predict_with_sdxl_detector(pil)
        heuristic   = analyze_heuristics(pil)

        ensemble = ensemble_image_predictions(
            eff_result, sdxl_result,
            heuristic_score=heuristic["heuristic_score"],
            fft_score=heuristic.get("fft_score"),
            clip_score=heuristic.get("clip_score"),
        )
        score = ensemble["fake_probability"]
        frame_scores.append(score)
        frame_details.append({
            "frame_index": frame["frame_index"],
            "fake_probability": round(score, 4),
            "models_used": ensemble["models_used"],
            "source": ensemble["source"],
        })
        print(f"[scan-video] Frame {i+1}/{len(frames)} (idx={frame['frame_index']}): score={score:.4f}  ({_time.time()-_t_frame:.1f}s)", flush=True)

    aggregate_score = float(np.mean(frame_scores)) if frame_scores else 0.5
    worst_idx       = int(np.argmax(frame_scores)) if frame_scores else 0
    worst_frame_pil = frames[worst_idx]["image"]

    # Convert worst frame to bytes for the explainer
    buf = _io.BytesIO()
    worst_frame_pil.save(buf, format="JPEG", quality=85)
    worst_frame_bytes = buf.getvalue()

    explainer_features = {
        "models_used": frame_details[worst_idx]["models_used"] if frame_details else [],
        "individual_scores": {},
        "heuristics": {},
        "metadata_status": "not_applicable",
        "ensemble_fake_probability": aggregate_score,
        "is_video": True,
        "frame_count": len(frames),
    }
    print(f"[scan-video] All frames done in {_time.time()-_t_start:.1f}s. Calling explainer...", flush=True)
    _t_exp = _time.time()
    try:
        explanation = generate_explanation(
            image_bytes=worst_frame_bytes,
            fake_prob=aggregate_score,
            features=explainer_features,
            target_language=target_language,
        )
        print(f"[scan-video] Explainer done in {_time.time()-_t_exp:.1f}s. Total: {_time.time()-_t_start:.1f}s", flush=True)
    except Exception as exc:
        print(f"[scan-video] Explainer failed: {exc}. Using template fallback.", flush=True)
        # Fallback verdict from score alone
        if aggregate_score >= HIGH_FAKE_THRESHOLD:
            verdict, conf = "Nakli", int(aggregate_score * 100)
        elif aggregate_score <= LOW_FAKE_THRESHOLD:
            verdict, conf = "Asli", int((1.0 - aggregate_score) * 100)
        else:
            verdict, conf = "Shak hai", 50
        explanation = {
            "verdict": verdict,
            "confidence_pct": conf,
            "explanation_en": f"Analyzed {len(frames)} frames. Average fake probability: {aggregate_score:.2f}",
            "explanation_local": "",
            "red_flags": [],
            "learn_more_tip": "",
            "source": "fallback",
        }

    return {
        "verdict":          explanation["verdict"],
        "confidence_pct":   explanation["confidence_pct"],
        "explanation_en":   explanation["explanation_en"],
        "explanation_local": explanation.get("explanation_local", explanation["explanation_en"]),
        "red_flags":        explanation.get("red_flags", []),
        "learn_more_tip":   explanation.get("learn_more_tip", ""),
        "source":           "ensemble",
        "frame_count":      len(frames),
        "frame_scores":     [round(s, 4) for s in frame_scores],
        "worst_frame_index": worst_idx,
        "video_metadata": {
            "total_frames": sampled["total_frames"],
            "fps":          sampled["fps"],
            "sampled_frames": len(frames),
        },
    }
